### ISSUE TITLE
CastConsumer error callback return values can be ignored

### ISSUE THREAD

**Issue by willlunniss** [googlecast/CastCompanionLibrary-android#109]
```onApplicationConnectionFailed``` and ```onConnectionFailed``` both have boolean return values. 
The documentation states that if you don't want CCL to show an error dialog, you should return false for these methods.

However, they are used in ways such as:

```
boolean showError = false;
synchronized (mVideoConsumers) {
	for (IVideoCastConsumer consumer : mVideoConsumers) {
		try {
			showError = showError || consumer.onApplicationConnectionFailed(errorCode);
		} catch (Exception e) {
			LOGE(TAG, "onApplicationLaunchFailed(): Failed to inform " + consumer, e);
		}
	}
}
```

Which means that it only takes one ```IVideoCastConsumer``` to return true (which all implementations do by default), and ```showError``` will be set.

As a number of CCL components contribute ```IVideoCastConsumer``` implementations (```VideoCastNotificationService```, ```VideoMediaRouteControllerDialog``` and ```VideoCastControllerFragment```), application implementations that return false can be ignored if any of those CCL components are currently activte, which causes the error dialogs to be shown.

**Comment by naddaf** [comment]
I have removed the return values and it is not the client's responsibility to show any error messages.
