### ISSUE TITLE
After pull 1.14

### ISSUE THREAD

**Issue by davidbilly** [googlecast/CastCompanionLibrary-android#145]
Hi @naddaf 

After i pull 1.14, i faced some issue while build .jar, error at BaseCastManager.java

public boolean isDeviceOnLocalNetwork() throws CastException {
        if (mSelectedCastDevice == null) {
            throw new CastException("No cast device has yet been selected");
        }
        return mSelectedCastDevice.isOnLocalNetwork(); >> The method isOnLocalNetwork() is undefined for the type CastDevice
    }

Thanks!

**Comment by naddaf** [comment]
Make sure you are compiling against Google Play Services 6.5.+

**Comment by davidbilly** [comment]
Do you means rev.22? Let me try update, thanks!

**Comment by davidbilly** [comment]
Hi @naddaf , Thanks it solved!
