### ISSUE TITLE
Disconnect  behavior is inconsistent (and different from a month ago?)

### ISSUE THREAD

**Issue by Groovee60** [googlecast/CastCompanionLibrary-android#151]
I first started investigating this library (along with the CastVideos app) in early December, prior to the latest round of changes. At that time, I noticed some sporadic inconsistencies when disconnecting via the Cast icon.. The video would usually (but not always) stop casting through the device to the TV. But with the latest changes, it always fails to stop casting, even though the icon state reflects that the device has been disconnected.

I understand that the design is for the casting to the TV/device to continue/resume if the Android app drops out unexpectedly. But if I explicitly disconnect the device via the icon/dialog, should the casting not stop?

**Comment by mokesmokes** [comment]
Perhaps related to this? https://code.google.com/p/google-cast-sdk/issues/detail?id=416

**Comment by Groovee60** [comment]
Yes, thanks for pointing me at that issue. It seems to confirm that the issue 1) used to be sporadic, 2) is now consistently failing, and 3) has not yet been fixed. I am now tracking that issue and awaiting a fix/update, and will close this redundant issue accordingly.
