### ISSUE TITLE
Not getting onMetaDataUpdated callbacks from Custom Receiver app

### ISSUE THREAD

**Issue by jonschmidt** [googlecast/CastCompanionLibrary-android#152]
We have filed a bug at StackOverflow with some more information as to what we are seeing on the receiver side : 

http://stackoverflow.com/questions/28192807/onremotemediaplayermetadataupdated-is-not-called-when-media-information-is-updat

We also found someone with the same problem from a year ago:
http://stackoverflow.com/questions/23397505/no-clear-way-to-alert-sender-applications-of-new-media-fetched-by-the-receiver-a

For the sender side, it is very simple. We are constructing a media info object, and sending it to the receiver :  https://gist.github.com/jonschmidt/1304427b859c8df88cf3

It is then playing fine. At the end of the playback, the receiver advances tracks, updates the metadata information, and the receiver never gets an onMetaDataUpdated callback, even though we continue getting status callbacks. Any idea why not?

**Comment by akovalev** [comment]
Another detall: the receiver app redefines `mediaManager#onEnded` callback in a way which is very similar to what you're doing in [this example](CastVideosPlaylist).

**Comment by naddaf** [comment]
This is not an issue on the sender side, nor CCL.
