### ISSUE TITLE
MediaChannelResult onResult success callback

### ISSUE THREAD

**Issue by rajendrag** [googlecast/CastCompanionLibrary-android#153]
Currently, In VideoCastManager's loadMedia has no success callback in mRemoteMediaPlayer.load(). It has only a onFailed callback when the result.getStatus() is not successful. A success callback would be helpful, for example to implement a playlist functionality.

**Comment by naddaf** [comment]
It is coming up in the next update with a signature like:

public void onMediaLoadResult(int statusCode);

where statusCoce is defined in com.google.android.gms.cast.CastStatusCodes (and possibly com.google.android.gms.common.api.CommonStatusCodes). A success is identified by com.google.android.gms.cast.CastStatusCodes#SUCCESS. 

This will replace the current onFailed callback and will be used for both failure and success.

**Comment by naddaf** [comment]
This was added in v2.0
