### ISSUE TITLE
The method setVolumeControlEnabled(boolean) is undefined for the type VideoMediaRouteControllerDialog

### ISSUE THREAD

**Issue by fanno** [googlecast/CastCompanionLibrary-android#155]
I get this error when trying to use this libery. ?

in:
com.google.sample.castcompanionlibrary.cast.dialog.video.VideoMediaRouteControllerDialogFragment line 35

**Comment by naddaf** [comment]
This is due to a backward-incompatible change in v22 of mediarouter support library. For now, you need to compile your app with v21. In future releases, we will address this one way or the other.

**Comment by mazadAnouar** [comment]
hi, 
i get this error when i trying use the liberary :com.google.sample.castcompanionlibrary
Error description : The method setVolumeControlEnabled(boolean) is undefined for the type VideoMediaRouteControllerDialog
severity :  Error
Element : VideoMediaRouteControllerDialogFragment.java
Location : line 35
App Compile: Platform 5.0.1 ApiLevel 21
Compiler Compliance Level : 1.7

**Comment by naddaf** [comment]
The new version of the library (v2.0 of CCL) has addressed this issue.
