### ISSUE TITLE
live stream incorrect behavior

### ISSUE THREAD

**Issue by fanno** [googlecast/CastCompanionLibrary-android#156]
pause/play of live stream media do not work correct. it need to stop/load..

togglePlayback may have similat problem

```java
      @Override
	public void onPlayPauseClicked(View v) throws CastException, TransientNetworkDisconnectionException, NoConnectionException {
		checkConnectivity();
		boolean isLive = isRemoteStreamLive();
		if (mState == MediaStatus.PLAYER_STATE_PLAYING) {
			if (isLive) {
				stop();
			} else {
				pause();
			}
		} else {
			if (mState == MediaStatus.PLAYER_STATE_IDLE && isLive) {
				loadMedia(getRemoteMediaInformation(), true, 0);
			} else if (mState == MediaStatus.PLAYER_STATE_PAUSED && !isLive) {
				play();
			}
		}
	}
```

**Comment by naddaf** [comment]
This is by design; the library doesn't call stop since that tears down the media session; instead the receiver, for live stream, needs to decide what makes sense for it to do.

**Comment by fanno** [comment]
if i use the code as is, i get error code 2100, what do i need to do ? then ?

**Comment by naddaf** [comment]
When do you get that; 2100 means request failed. What does your receiver log show?

**Comment by fanno** [comment]
i am using the default reciver, the app is free so i dont have funds to host a reciver.

and i get the error when the stream is paused and i try to start it again. (if live stream)

**Comment by naddaf** [comment]
I suggest you create your own Styled receiver (which is the same code as the Default receiver) and host that on, say, app engine for free (for testing purposes) and look at the logs and address your issues. Once it is done, you can bring down the app engine; this way you have a development set up that you have some control over and you get the benefit of seeing the receiver logs. Your production remains on the default receiver so you don't need to spend any funds on that.

**Comment by fanno** [comment]
I don't have good enough knowledge  to try that yet. I'll live with modified version for now.

Thanks for your time
