### ISSUE TITLE
MediaStatus always buffering 

### ISSUE THREAD

**Issue by mehtam2** [googlecast/CastCompanionLibrary-android#157]
I’m on latest version of CCL. I’m having an issue where in for VideoCastManager.java class  inside method onRemoteMediaPlayerStatusUpdated I almost always get mRemoteMediaPlayer.getMediaStatus() = buffering?  Meanwhile on TV I see video progressing fine. 

Could you suggest as what could be going wrong?

**Comment by naddaf** [comment]
What app are you using?

**Comment by mehtam2** [comment]
PostTV-Receiver-Prod as cast receiver

**Comment by naddaf** [comment]
Is this happening with CastVideos-android app? I am not able to reproduce that. Please confirm.

**Comment by mehtam2** [comment]
Let me try on that app, will get back to you soon.

**Comment by mehtam2** [comment]
CastVideos-android works perfectly fine.

**Comment by naddaf** [comment]
Then I suggest you contact the developers of the PostTV to see what they are doing on their side, thanks.
