### ISSUE TITLE
java.lang.IllegalArgumentException: trackIds cannot be null or empty

### ISSUE THREAD

**Issue by fanno** [googlecast/CastCompanionLibrary-android#158]
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at com.google.android.gms.cast.RemoteMediaPlayer.setActiveMediaTracks(Unknown Source)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at com.google.sample.castcompanionlibrary.cast.VideoCastManager.setActiveTrackIds(VideoCastManager.java:2192)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at com.google.sample.castcompanionlibrary.cast.player.VideoCastControllerFragment.onTracksSelected(VideoCastControllerFragment.java:778)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at com.google.sample.castcompanionlibrary.cast.VideoCastManager.notifyTracksSelectedListeners(VideoCastManager.java:2384)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at com.google.sample.castcompanionlibrary.cast.tracks.ui.TracksChooserDialog$1.onClick(TracksChooserDialog.java:79)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:160)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at android.os.Looper.loop(Looper.java:211)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at android.app.ActivityThread.main(ActivityThread.java:5321)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at java.lang.reflect.Method.invoke(Native Method)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at java.lang.reflect.Method.invoke(Method.java:372)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
> 03-21 23:14:40.714: E/AndroidRuntime(16444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

I get this error when i try to chose "no" subtitels 

so i cant disable subtitels once started.

https://developer.android.com/reference/com/google/android/gms/cast/RemoteMediaPlayer.html

>public PendingResult<RemoteMediaPlayer.MediaChannelResult> setActiveMediaTracks (GoogleApiClient apiClient, long[] trackIds)
>
>Sets the active media tracks.
>
>Parameters
>apiClient	The API client with which to perform the operation. Must not be null.
>trackIds	The media track IDs. If an empty array, the current set of active trackIds will be removed.
>Returns
>A PendingResult which can be used to track the progress of the request.
>Throws
>IllegalArgumentException	If trackIds is null.

how ever it seems that it throw error if empty.

Can anything be done about this ? if so what ?

**Comment by naddaf** [comment]
This is an issue in the Play Services and is fixed in the upcoming release. Meanwhile, there isn't much you can do except commenting out that line which sets the active tracks to empty.

**Comment by fanno** [comment]
it comes from your examble. tho as far as i can tell..

i have added a try/catch

```java
	public void setActiveTrackIds(long[] trackIds) {
		if (null == mRemoteMediaPlayer || null == mRemoteMediaPlayer.getMediaInfo()) {
			return;
		}

		try {
			mRemoteMediaPlayer.setActiveMediaTracks(mApiClient, trackIds).setResultCallback(new ResultCallback<MediaChannelResult>() {
				@Override
				public void onResult(MediaChannelResult mediaChannelResult) {
					LOGD(TAG, "Setting track result was successful? " + mediaChannelResult.getStatus().isSuccess());
					if (!mediaChannelResult.getStatus().isSuccess()) {
						LOGD(TAG, "Failed since: " + mediaChannelResult.getStatus() + " and status code:" + mediaChannelResult.getStatus().getStatusCode());
					}
				}
			});
		} catch(IllegalArgumentException e) {
			e.printStackTrace();
		}
	}
```

Do you happen to know when i can expect this fixed ? is there way i can keep track of this ?

**Comment by fanno** [comment]
ohh and thanks for fast reply.

**Comment by naddaf** [comment]
Since that is in Play Services, I can't give you an exact date but it is not that far; when we release a new Play Services, we usually post a blog on that front with the new changes and features that are added, so you might want to monitor that.

**Comment by fanno** [comment]
Could you tell me what page that would be ? and can i subscribe to updates some where, so i don't have to do it manually?

( sorry for asking i am quite new to this in android apps )

**Comment by naddaf** [comment]
What is your current version of play services?

**Comment by fanno** [comment]
rev 22
as i checked it there is now a 23, trying to update it now. pehaps it is fixed.

**Comment by fanno** [comment]
seems to be fixed in 23, sorry for wasting your time. i did not think to check for updates =/

**Comment by naddaf** [comment]
Good to hear that it is fixed.

**Comment by fanno** [comment]
Just a final thought, is this library intended to be used in production? or should i be "cloning" it and creating my own "version" just curious since it is called "com.google.sample"

**Comment by naddaf** [comment]
Very soon (hopefully before the end of this weekend),  I will update the library with a modified version that also has a different package name (see https://plus.google.com/+AliNaddaf1/posts/3vvM6H8uxRZ for more details). The intent is to use this in production.

**Comment by fanno** [comment]
Thanks very much once again =), thanks for your time !!! i have added watch on the repo and you your g+ =) i'll try and heek up to date =)

**Comment by fanno** [comment]
I thought i would ask one more question since you seem like a expert! i did search the web but without any success so i suspect it is not possible.

Say am i am playing a live stream. I have info running checking for updates in the stream info (current program streamed by the station.) with title and image and such ..

is there a way to "update" MediaInfo on an existing stream so at least the phone will display the correct image ect in the notifications ect ect ?

-Thanks

**Comment by fanno** [comment]
as far as i can find only way would be just to load the live stream again with the new info in the mediainfo ?

**Comment by naddaf** [comment]
I am not sure if I understand your question. Where do you get the updated info from? Where do you want to update the info to show the user?

**Comment by fanno** [comment]
from a 3rd part, i download json requests that holds info what is currently playing in the live stream.

This i also add to the Mediainfo.title/subtitel image .. ect the actual stream url don't change

My question is. Can i update the info, without "restart" the live stream? with the updated image/title/subtitle

**Comment by naddaf** [comment]
I am still not clear. Lets say you do get the updated info from a server. Where do you want to show the new and updated info? If it is on the sender, then are you asking if in CastControllerActivity of the CCL one can update the images without reloading? If that is what you are asking, currently that component in CCL doesn't do that; it is not too difficult to extend it to do that but right now it doesn't.

**Comment by fanno** [comment]
My english is not my first language so that would prop early be why =)

I will try again CLL and the controlers (that be mini controller, lock screen/notification), they can as far as i can tell get the info from:

```java
	public MediaInfo getRemoteMediaInformation() throws TransientNetworkDisconnectionException, NoConnectionException {
		checkConnectivity();
		checkRemoteMediaPlayerAvailable();
		return mRemoteMediaPlayer.getMediaInfo();
	}
```

So what is missing as as far as i can tell is a way to (update the mediainfo inside "RemoteMediaPlayer"), and that is as far as i can tell not possible.

buy yes i could pehaps ovewrite the getRemoteMediaInformation and have it do something different, but then i guess the mediainfo would not reflect what the chromecast has on it's end and if we try to reconnect it won't show correct info? it would be using the old info ? (this is of cause assuming, am correct, whitch ofcause may not be the case)

What parts were you thinking i should overwrite/extend ? pehaps that would give and idea

-Thanks

**Comment by fanno** [comment]
And yes it is on the sender. (android)

**Comment by naddaf** [comment]
The proper way for addressing this type of features is to handle most of it in the receiver. As you had observed, even if we do something on the sender side, we won't be able to extend that easily across reconnects, or other senders when they get connected, nor the receiver will be able to adjust. Instead, this kind of dynamic changes for a live stream, in my opinion, should be handled in the receiver. Receiver should include logic to be able to go to the appropriate server and obtain updated metadata; some of it may be embedded int he live stream and some may be fetched out-of-band. Once receiver obtains that updated info, then it can update its own UI (on the receiver) and can also send MetaData update messages to all connected senders so all of them reflect the new metadata (titles, images, etc). CCL handles metadata update messages correctly, including in mini-controllers, VideoCastController and elsewhere so handling this in the receiver gives you a complete and robust solution, at least IMHO.

**Comment by fanno** [comment]
Once again thanks for your excellent response.

I will put it on todo list if i decide to create custom receiver.

thank you so very much
