### ISSUE TITLE
Log.d(TAG, "Build version is: " + Build.VERSION.SDK_INT);

### ISSUE THREAD

**Issue by fanno** [googlecast/CastCompanionLibrary-android#164]
Hello this is a very minor question/observation

this is the only location out side of LogUtils where log.* is used should it not be LOGD instead ?
```java
    /*
     * Build the RemoteViews for the notification. We also need to add the appropriate "back stack"
     * so when user goes into the CastPlayerActivity, she can have a meaningful "back" experience.
     */
    private RemoteViews build(MediaInfo info, Bitmap bitmap, boolean isPlaying)
            throws CastException, TransientNetworkDisconnectionException, NoConnectionException {
        Log.d(TAG, "Build version is: " + Build.VERSION.SDK_INT);
....
...
```
P.S.
I recently change to android studio so i am trying to figure out why this was the only CCL log event i am getting (still not figure out why this is..) in eclipse i was getting all log events when in debug (not release).

I know this is properly not related to you, but would you happen to know why or guess to a reason why logs are not happening or it seems that it is building release ? for ccl ?

-Thanks

**Comment by naddaf** [comment]
Sorry for late response. As for your first question, that should be LOGD as well, I will try to remember to update that in the next release. As for your second question, please take a look at the LogUtils where LOGD is defined and change the value of DEBUG to true and see if that addresses your problem.
