### ISSUE TITLE
Is setStopOnDisconnect not working anymore?

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#169]
Sorry forgot to write a description. 

I am trying the cast videos sample and when I disconnect it stops playback. I remember it didn't use to do that. Has that functionality changed?

**Comment by naddaf** [comment]
If you are the only connected device, then that is expected and recommended by the UX Checklist.

**Comment by mntgoat** [comment]
So is the setStopOnDisconnect method kind of useless then?
