### ISSUE TITLE
Possible Interference With KeyCut App?

### ISSUE THREAD

**Issue by whitedavidp** [googlecast/CastCompanionLibrary-android#171]
I think I have encountered a small problem with Web Video Caster, an app who's author tells me it was developed using this library. The app is at <https://play.google.com/store/apps/details?id=com.instantbits.cast.webvideo&hl=en>. The same problem occurs with several other apps including this one <https://play.google.com/store/apps/details?id=mb.videoget&hl=en> but I have no confirmation that these apps use this library.

Web Video Caster interferes with another app I use called KeyCut <https://play.google.com/store/apps/details?id=com.lennox.keycut&hl=en>. KeyCut works in conjunction with a really cool little device <http://www.banggood.com/Protable-iKey-Smart-Quick-Click-Press-Button-Dust-Proof-Plug-p-943850.html> that plugs into my phone's headphone jack. What happens is that the device acts like the buttons on a wired headset and the app triggers actions based upon the pattern of button presses it "sees".

I have discovered that after using and disconnecting/exiting Web Video Caster, no button presses seem to get delivered to the KeyCut app.

At first, I presumed this was related to the casting mechanism in general. But since things seem to work OK after using Google Play Movies and YouTube, the author of Web Video Caster suggests that the issue may be in this library rather than being a generalized problem withing the whole casting mechanism.

Could this be the case?

**Comment by naddaf** [comment]
If the authors of an app believe there is an issue in CCL, they would need to file a bug themselves and provide more info, there is nothing here to take any action on.

**Comment by whitedavidp** [comment]
Well, here I am taking the time to try and let you folks know and it 
gets about 1 second's consideration. I know that what I have reported is 
not very detailed. But perhaps you could tell me if somewhere in the 
code of this library there is media button handling. It could at least 
save me searching through the code myself.

Thanks

naddaf wrote:

**Comment by naddaf** [comment]
Not sure what you mean by Media Button handling; if you are referring to the broadcast receiver for android.intent.action.MEDIA_BUTTON action, then the library doesn't do that; such handling is usually registered in the "application" manifest (by application, I am referring to the application that uses this library), but I am not sure what you are referring to. I suggest you try other apps that use CCL to see if this happens for them as well, or not (for example CastVideos-android sample)

**Comment by whitedavidp** [comment]
What I mean by media button handling is not necessarily as technical as your suggest - but I am not familiar with it. What I mean is that my phone stops responding to button presses from a wired headset after casting. Note: I must actually do some casting before this fails. It is not like just starting the apps do this.

I tested with the Cast Videos app last night and it suffers the same fate as the Web Video Caster app. So far the only apps that seem to be exempt from this problem are "official" Google apps - Play Movies and YouTube.

**Comment by mntgoat** [comment]
I can confirm this is happening. Basically VideoIntentReceiver.onReceive continues to be called even after video playback has ended. I see a call to removeRemoteControlClient() happening on disconnect but for some reason the button presses (I'm using a pressy) are still being trapped by VideoIntentReceiver.onReceive.

**Comment by naddaf** [comment]
This is now fixed
