### ISSUE TITLE
Notification on AndroidWear malfunction

### ISSUE THREAD

**Issue by seventhmoon** [googlecast/CastCompanionLibrary-android#178]
Tested on 
LG G Watch 5.0.2 (Android 5.0.2)
Galaxy Gear Live (Android 5.0.2)

The notification shows a play/pause button, but the button is not working, it cannot play / pause.

Same code works on Android Wear running 4.4W.

**Comment by seventhmoon** [comment]
Tested on 
LG G Watch 5.0.2 (Android 5.1)

Issue still occurs.

**Comment by naddaf** [comment]
In 2.3, MediaSessionCompat is used and that should address this issue.
