### ISSUE TITLE
Live streams cannot be resumed from the mini controller

### ISSUE THREAD

**Issue by utkuutkan** [googlecast/CastCompanionLibrary-android#181]
The `MediaStatus` is expected to become `PLAYER_STATE_IDLE` when a live stream is stopped, but instead it becomes `PLAYER_STATE_PAUSED`. And due to the following check in `VideoCastManager`, the `play()` method never gets called when the play button is tapped in the mini controller.

    boolean isLive = isRemoteStreamLive();
    if ((mState == MediaStatus.PLAYER_STATE_PAUSED && !isLive)
        || (mState == MediaStatus.PLAYER_STATE_IDLE && isLive)) {
      play();
    }

This is not an issue with the actual cast controller, as `VideoCastControllerFragment` plays the stream whether the current `MediaState` is `PLAYER_STATE_PAUSED` or `PLAYER_STATE_IDLE`.

**Comment by naddaf** [comment]
Is this a custom receiver?

**Comment by naddaf** [comment]
You need to have a custom receiver; please read the section "Live Streams" in the CCL's documentation where it describes what it expects the receiver to return as the status.
