### ISSUE TITLE
Can't not change the style for Text Tracks

### ISSUE THREAD

**Issue by iceteahh** [googlecast/CastCompanionLibrary-android#183]
I have followed the document of ccl "Changing the Style for Text Tracks" but it seem to be not working.
The Preference Activity shown up  and i adjusted some values but the subtitles displayed on receiver app didn't change it's style. What i'm missing?

**Comment by naddaf** [comment]
Does it wok when you run the CastVideos-android app?

**Comment by iceteahh** [comment]
I just check this feature of your sample app and it does not work too. My device run android 5.0.2 and it does not have caption settings in accessibility so I try to use your CaptionsPreferenceActivity.

**Comment by naddaf** [comment]
Android since KitKat has the captions setting so I am not sure what type of build you are running on your phone.Please provide some logs, screenshot and such.

**Comment by iceteahh** [comment]
OK i check it with a new device run android 4.4.2 it work. But there is no options let me style the edge of text. All of options displayed  here have the background. Is there anyway that i can use edge instead background?

**Comment by iceteahh** [comment]
OK i just check it with a new device run android 4.4.2 and it worked. Thanks for your support!

**Comment by iceteahh** [comment]
But when i try to use CaptionsPreferenceActivity i get that on logcat "Failed to update the captions style., code: 2103".

**Comment by naddaf** [comment]
You can find the meaning of this code here: https://developers.google.com/android/reference/com/google/android/gms/cast/CastStatusCodes#REPLACED
