### ISSUE TITLE
Cast manager activity closed due to race condition when casting a new item

### ISSUE THREAD

**Issue by xtreme-bozhidar-lenchov** [googlecast/CastCompanionLibrary-android#185]
From the change log, I believe this issue was introduced with the V2.1 update (Queue API changes). We upgraded from V2 to V2.1.1 recently and just noticed it:

1. Connect to Chromecast
2. Cast an item
3. Back out from Cast Manager screen into the app again
4. Click on another item in the app (this immediately starts casting the new content in our app; no queuing at the moment).

Expected: Cast Control screen pops up and loads info for item 2.
Actual: Cast Control screen pops up for half a second, then closes.

I narrowed this down to VideoCastManager::onRemoteMediaPlayerStatusUpdated which ends up calling VideoCastControllerFragment::updatePlayerStatus which in turn calls VideoCastControllerActivity::closeActivity which terminates the Cast Manager screen. When casting of the second item occurs, I see:

* Media Status Player State being PLAYER_STATE_IDLE
* Media Status Idle Reason being IDLE_REASON_INTERRUPTED
* Media Status Loading Item ID being INVALID_ITEM_ID (0)

One possible workaround is in the VideoCastControllerFragment instead of immediately calling closeActivity to check the media queue after 5 seconds of the IDLE_REASON_INTERRUPTED being received. If it is still empty, we call closeActivity, but if we detect the second item at that point we don't do anything. It's not ideal (e.g. are 5 seconds enough on a slow network), but hopefully we detect there is a second item being loaded by then.

**Comment by naddaf** [comment]
I have made a change in 2.2 to address that, please give it a try.
