### ISSUE TITLE
Live stream notification persist even after live stream is stopped

### ISSUE THREAD

**Issue by davidgarsan** [googlecast/CastCompanionLibrary-android#186]
After stopping a live stream by pressing the stop button in both notification or lockscreen playback controls, the notification dismiss. But as soon as the app goes to background, the notification appears again showing the stop button despite there is no content playing in the Chromecast device.

**Comment by naddaf** [comment]
What do you do on the receiver side when user presses the "stop" button in a liv stream? I presume you have a custom receiver?

**Comment by serginator** [comment]
Hi. On the receiver side, the media manager (`cast.receiver.MediaManager(videoElement)`) has an onStop handler, we extend it to emits an internal event, resets the application state, go to splash screen, resets the player and then calls the original onStop.

**Comment by naddaf** [comment]
The stop button on the sender sends "pause" event to the receiver and the receiver should handle that accordingly. In response, receiver should set the status to IDLE with reason CANCELED (see the CCL documentation); ts is a convention that CCL has decided to use since there is no clear state to reflect this case for live stream. Is that what your receiver is doing?

**Comment by naddaf** [comment]
Closing due to lack of feedback.

**Comment by serginator** [comment]
Sorry for not answering, this is a month of vacations.

As I said on 13 Jul, we extend the mediaManager.onStop method to emit some internal events and reset our player, and then we call the original mediaManager.onStop method, which according to the documentation sets the idle reason to Cancelled: 
 
> Processes the stop event. The default behavior is to call resetMediaElement, with idle reason CANCELLED, and broadcast the status providing the incoming requestId.
