### ISSUE TITLE
Cannot get back MediaStatus with requestStatus when the MediaInfo on the receiver is changed after re-join the session

### ISSUE THREAD

**Issue by mssjsg** [googlecast/CastCompanionLibrary-android#187]
Hi, currently our project requires that the receiver to be able to fetch the next episode data (and set mediaInformation on the receiver side) when the current episode finished playing. However, when the receiver is playing the new episode, and I do the following steps:
1. completely kill the app (by killing the app in DDMS)
2. launch the app
3. the receiver is connected but no minicontroller is displayed

I traced and found that RemoteMediaPlayer.requestStatus() in onApplicationConnected cannot respond and mediaStatus in the remoteMediaPlayer remains null so minicontroller cannot display.

It was all fine in playing the first episode.

I spent a lot of time to dig this issue but I can't really resolve. Is this a bug in the castCompanionLibrary or Android sdk? Thanks in advance.

**Comment by naddaf** [comment]
Following the same steps, I cannot reproduce this in CastVideos-android app that uses CastCompanionLibrary so I tend to believe the issue is in your sender or receiver code.

**Comment by mssjsg** [comment]
Hi naddaf, thanks for verifying, do you try this when the receiver plays the video after the receiver fetch the next video data and mediaInformation is changed on the receiver side(i.e. the receiver is playing the second episode)?
Before the second episode, everything is fine on my side too.
