### ISSUE TITLE
MediaInfo is not updated in RemoteMediaPlayer after receiver calling setMediaInformation

### ISSUE THREAD

**Issue by mssjsg** [googlecast/CastCompanionLibrary-android#188]
After the receiver finished playing the first video, the receiver will fetch the next videos data and do setMediaInformation. The android sender app is not notified about the changes in MediaInfo.
onMetadataUpdated is not triggered and the RemoteMediaPlayer.getMediaInfo() still returns the data of the first video so the meta data and duration are all wrong when the receiver auto-play the second video.

**Comment by naddaf** [comment]
This is not an issue with the CCL, it is up to your receiver to send the appropriate messages to the sender.
