### ISSUE TITLE
Use xml drawables for media route controller and cast notification icon

### ISSUE THREAD

**Issue by phpeng-ms** [googlecast/CastCompanionLibrary-android#189]
CCL currently uses alias resource XMLs for the MiniController (e.g. drawable/ic_mini_controller_*.xml) resources but uses hardcoded resource IDs for VideoMediaRouteControllerDialog and VideoCastNotification. This makes it difficult for implementing apps to override these resources if they want to customize the UI.

Suggested fix would be adding new drawable/ic__media_route_controller_*.xml and drawable/ic_cast_notification_icon.xml aliases. See https://github.com/phpeng-ms/CastCompanionLibrary-android/commit/575fa26ae8e649f78dedc0c045708fe45f8b174e for example changes.

**Comment by naddaf** [comment]
New aliases were defined in 2.2
