### ISSUE TITLE
VideoCastNotificationService no VideoCastManager instance was found

### ISSUE THREAD

**Issue by cdilks** [googlecast/CastCompanionLibrary-android#191]
The application give a "No VideoCastManager instance was found" error if your application is closed via the recents screen before playing a video.

Steps to recreate.
1. Launch Application
2. Connect to Chromcast, but do not start playing any content. (receiver shows splash screen on Chromecast)
3. open recents and close app.

VideoCastNotificationService.java
Line 92 causes the VideoCastManager to throw IllegalStateException showing "Uunfortunte, APP_NAME has stopped"

**Comment by naddaf** [comment]
I just tried that on my N6 and I don't see such error/exception. Line 92 doesn't point to any executable line in VideoCastNotificationService so you might want to update your library and try again and provide complete stack trace and more info about the device, etc.

**Comment by cdilks** [comment]
This was on the most up to date release v2.1.1.

The line is
mCastManager = VideoCastManager.getInstance();

It was the 3rd executable line of oncreate

**Comment by naddaf** [comment]
Where and how do you initialize your VideoCastManager in your app?

**Comment by cdilks** [comment]
It is being initialized the first time it is needed in the oncreate of the first screen after a user logs in.

This code lives inside our application class
<pre>    
private static VideoCastManager mCastMgr = null;
.
.
.
public static VideoCastManager getCastManager(Context context) {
        if (null == mCastMgr) {
            mCastMgr = VideoCastManager.initialize(context, APPLICATION_ID,
                    null, context.getString(R.string.dailyburn_namespace));
            mCastMgr.enableFeatures(
                            VideoCastManager.FEATURE_NOTIFICATION |
                            VideoCastManager.FEATURE_LOCKSCREEN |
                            VideoCastManager.FEATURE_DEBUGGING |
                            VideoCastManager.FEATURE_WIFI_RECONNECT);
        }

        return mCastMgr;
    }
</pre>

**Comment by naddaf** [comment]
That is not the right way to initialize the VideoCastManager; the issue with your approach is that if the application is killed by the framework, when the service wants to be restarted, it encounters an uninitalized VideoastManager. The proper way is to do as I do it in the CastVideos-android in the onCreate() of the Application class:

    @Override
    public void onCreate() {
        super.onCreate();

        // initialize VideoCastManager
        VideoCastManager.
                initialize(this, APPLICATION_ID, VideoCastControllerActivity.class, null).
                setVolumeStep(VOLUME_INCREMENT).
                enableFeatures(VideoCastManager.FEATURE_NOTIFICATION |
                        VideoCastManager.FEATURE_LOCKSCREEN |
                        VideoCastManager.FEATURE_WIFI_RECONNECT |
                        VideoCastManager.FEATURE_CAPTIONS_PREFERENCE |
                        VideoCastManager.FEATURE_DEBUGGING);

    }

Then, when the application is killed by the framework and the service wants to restart, framework first creates a new instance of the Application, hence we have the VideoCastManager instantiated and initialized and then the service gets started and you won't run into that issue.

**Comment by cdilks** [comment]
Ah that was it! Thank you!
