### ISSUE TITLE
VideoCastControllerActivity does not respect VideoCastManager.setNextPreviousVisibilityPolicy()

### ISSUE THREAD

**Issue by hudren** [googlecast/CastCompanionLibrary-android#193]
The `VideoCastManager` contains a field for determining the visibility of the Prev and Next buttons and passes this preference as an EXTRA to the `Intent` when starting the `VideoCastControllerActivity`.

    intent.putExtra(EXTRA_NEXT_PREVIOUS_VISIBILITY_POLICY, mNextPreviousVisibilityPolicy);

However, the `VideoCastControllerActivity` does not check this EXTRA and always uses its default value of `VideoCastController.NEXT_PREV_VISIBILITY_POLICY_DISABLED`.

**Comment by naddaf** [comment]
It is it being taken care of in VideoCastControllerFragment#onActivityCreated()

**Comment by hudren** [comment]
The implementation doesn't always work. Pressing back from the VideoCastControllerActivity to it's parent activity, then pressing on the mini controller, displays the VideoCastControllerActivity with the previous and next buttons displayed.
