### ISSUE TITLE
Immersive Mode for VideoCastControllerActivity cannot be disabled

### ISSUE THREAD

**Issue by hudren** [googlecast/CastCompanionLibrary-android#194]
IMO, the `VideoCastControllerActivity` is a poor candidate for hiding the navigation controls since the *user is not consuming content* on this screen as is more likely to want to navigate elsewhere to check email, etc while their content is playing on the big screen. As things stand, the user has to make the navigation controls visible before using their device for other tasks.

Please, please provide an override to allow developers to disable this behavior. Something like controlling the visibility of the Prev and Next buttons through the `VideoCastManager` would be sufficient.

**Comment by hudren** [comment]
There is also a bug where Immersive mode does not always get enabled. With the `VideoCastControllerActivity` being displayed (on a Lollipop device), press the Home button, then the app icon from the launcher to display the `VideoCastControllerActivity`. Immersive mode will not be enabled.

When not using Immersive mode, the status bar is a grey color. Generally, the status bar is a darker variant of the action bar background. Since it fades to black, it makes sense for the action bar to also be black.

**Comment by naddaf** [comment]
Fixed in 2.3. You can control that by using VideoCastManager.setImmersive() method.
