### ISSUE TITLE
Multi-process application - only 1 process is connected

### ISSUE THREAD

**Issue by blundell** [googlecast/CastCompanionLibrary-android#195]
We have two Activities that run in separate processes but the same app.

```xml
<activity
      android:name=".PlayerActivity"
      android:process=":player"/>

<activity android:name=".MainActivity" />
```

When we connect to a Chrome Cast from the PlayerActivity and then navigate to the MainActivity the CastManager does not think we are connected (and so the cast button on tool bar shows disconnected). In fact we can connect both activities to the Chrome Cast separately which is not what we want!

Is this a known issue?
Could you direct me to somewhere in the code that is doing this? (so I can fix it if you are not going to soon).

**Comment by blundell** [comment]
It's the fact that we call:

`VideoCastManager videoCastManager = VideoCastManager.initialize(context, BuildConfig.CHROMECAST_APP_ID, null, null);`

in our application class( *or anywhere*) and with two processes this leads to two versions of the VideoCastManager - meaning we have two connections.

I guess two processes & ChromeCast is not possible with the current `VideoCastManager` architecture.

**Comment by naddaf** [comment]
Multi-process is currently not in the scope, mostly because I haven't worked with such scenarios to see what needs to be done.

**Comment by blundell** [comment]
at least it's confirmed as not working :+1: thanks

**Comment by naddaf** [comment]
To tell you the truth, I have never tested that to see if it works or not; it hasn't been a goal to ensure it works since the usage of multi-process apps is small; I do like to get that working so when I get a bit of free time, I will investigate what needs to be done; if you come up with a simple solution, please do let me know.
