### ISSUE TITLE
Orientation changed when loading

### ISSUE THREAD

**Issue by PetrSklenicka** [googlecast/CastCompanionLibrary-android#197]
I wrote about my issue here: http://stackoverflow.com/questions/31879449/castcompanionlibrary-orientation-changed-when-loading?noredirect=1#comment51897732_31879449

In short, when I start VideoCastControllerActivity, there is visible progress bar and controllers for play/pause, etc, are not visible, because content is loading - it is fine. If I change an orientation of device, the controllers for play/pause, etc, are now visible, but content is still loading - this is undesirable behavior.

**Comment by naddaf** [comment]
I am not able to reproduce this, maybe I am not doing the same thing as you are. In CastVideos-android, I removed the restriction on the VideoCastControllerActivity so it can be both portrait and landscape. Now when I am in that activity, I use the seekbar to move to a seek to a different point. While it is still seeking and I see a progressbar, I change the orientation to landscape and I see the very same thing; the play/pause is hidden, the  progressbar is shown and the seekbar is also visible and as soon as the seek ends, I see the play/pause as well.

**Comment by PetrSklenicka** [comment]
Yes, you are right, this approach works fine. The bug mentioned above can be reproduced by following these steps. 

1. Select a video, which you want to play.
2. Connect to Chromecast (or something else) and start with remote playing.
3. The VideoCastControllerActivity is started and video is loading now (it is first loading, no seek is needed)
4. When the video is loading, Play/Pause button and Seekbar are not visible. Right now you you should change the orientation.
5. The video is still loading, but now you can see that Play/Pause and SeekBar are now visible, but video is still loading. It is "first loading of video" before video has started.

In case, that video is loaded and it is playing, then seeking and changing orientation works perfectly. The mentioned bug is reproducible only during the initial loading of video.

**Comment by naddaf** [comment]
In CastVideos-android app, we don't start the Controller activity automatically; can you try that app and come up with some repr0 steps please?

**Comment by naddaf** [comment]
Closed due to lack of response
