### ISSUE TITLE
Cast icon still appears as connected after onApplicationConnectionFailed

### ISSUE THREAD

**Issue by ChadMcQuillen** [googlecast/CastCompanionLibrary-android#203]
From SO:

http://stackoverflow.com/questions/32291300/how-to-recover-from-onapplicationconnectionfailed-errorcode-8-internal-er

Please note that the cast receiver actually launched.  My cast receiver loads a couple images at startup and doesn't change its application state to 'Ready' until these load.  This time is in terms of seconds and has the affect of opening up the window where the launch process could be subjected to intermittent failures (as is the case with my network).

I have debug logs if you need to see.

**Comment by naddaf** [comment]
Let's address the issue where your cast icon shows connected even if you receive onApplicationConnectionFailed(). Since I don't have any app to use the DataCastManager with, I would need you to try out a possible solution. Could you open DataCastManager and find onApplicationConnectionFailed() method and replace that with the following and let me know if that fixes that particular issue or not?

    @Override
    public void onApplicationConnectionFailed(int errorCode) {
        if (mReconnectionStatus == RECONNECTION_STATUS_IN_PROGRESS) {
            if (errorCode == CastStatusCodes.APPLICATION_NOT_RUNNING) {
                // while trying to re-establish session, we found out that the app is not running
                // so we need to disconnect
                mReconnectionStatus = RECONNECTION_STATUS_INACTIVE;
                onDeviceSelected(null);
            }
        } else {
            for (DataCastConsumer consumer : mDataConsumers) {
                consumer.onApplicationConnectionFailed(errorCode);
            }
            onDeviceSelected(null);
            if (mMediaRouter != null) {
                LOGD(TAG, "onApplicationConnectionFailed(): Setting route to default");
                mMediaRouter.selectRoute(mMediaRouter.getDefaultRoute());
            }
        }
    }

**Comment by ChadMcQuillen** [comment]
Yes, the cast icon now shows as being disconnected.

**Comment by naddaf** [comment]
Good. I will update the library with this fix soon. Meanwhile, if you have other issues with the DataCastManager, please open separate tickets so I can address those as well.

**Comment by naddaf** [comment]
Addressed in 2.4
