### ISSUE TITLE
onConnectivityRecovered() sometimes called after onApplicationConnectionFailed()

### ISSUE THREAD

**Issue by ChadMcQuillen** [googlecast/CastCompanionLibrary-android#204]
In current library as well as trial fix for Issue #203 sometimes onConnectivityRecovered() gets called after onApplicationConnectionFailed().

`08-29 21:52:18.048  16369-16369/com.bannerstonesoftware.XYZ D/ccl_BaseCastManager﹕ [v2.3.2] launchApplication() -> failure result
08-29 21:52:18.048  16369-16369/com.bannerstonesoftware.XYZ D/CastedTournament﹕ onApplicationConnectionFailed() - errorCode:8
08-29 21:52:18.065  16369-16369/com.bannerstonesoftware.XYZ D/ccl_BaseCastManager﹕ [v2.3.2] disconnectDevice(true,false)
08-29 21:52:18.065  16369-16369/com.bannerstonesoftware.XYZ D/ccl_BaseCastManager﹕ [v2.3.2] mConnectionSuspended: true
08-29 21:52:18.066  16369-16369/com.bannerstonesoftware.XYZ D/ccl_BaseCastManager﹕ [v2.3.2] onDisconnected() reached
08-29 21:52:18.066  16369-16369/com.bannerstonesoftware.XYZ D/CastedTournament﹕ onDisconnected()
08-29 21:52:18.066  16369-16369/com.bannerstonesoftware.XYZ D/ccl_DataCastManager﹕ [v2.3.2] onApplicationConnectionFailed(): Setting route to default
08-29 21:52:18.103  16369-16369/com.bannerstonesoftware.XYZ D/ccl_CastMediaRouterCal﹕ [v2.3.2] onRouteUnselected: route=MediaRouter.RouteInfo{ uniqueId=com.google.android.gms/.cast.media.CastMediaRouteProviderService:607a6a186b6c170b1a223cc7b6d27646, name=McQuillen Poker Room, description=Poker Tournament, enabled=true, connecting=true, canDisconnect=false, playbackType=1, playbackStream=-1, volumeHandling=0, volume=0, volumeMax=20, presentationDisplayId=-1, extras=Bundle[mParcelledData.dataSize=596], settingsIntent=null, providerPackageName=com.google.android.gms }
08-29 21:52:18.103  16369-16369/com.bannerstonesoftware.XYZ D/ccl_BaseCastManager﹕ [v2.3.2] disconnectDevice(true,false)
08-29 21:52:20.523  16369-16369/com.bannerstonesoftware.XYZ D/ccl_BaseCastManager﹕ [v2.3.2] onConnected() reached with prior suspension: true
08-29 21:52:20.523  16369-16369/com.bannerstonesoftware.XYZ D/CastedTournament﹕ onConnectivityRecovered()`

**Comment by naddaf** [comment]
Can you explain why you are getting the onApplicationConnectionFailed()? Is it due to the network issues that you had mentioned?

**Comment by ChadMcQuillen** [comment]
Yes.  I'll typically see something like this:

D/CastDeviceController( 1440): [controller-0025 API] disconnecting due to heartbeat timeout
D/CastSocket( 1440): [controller-0025 API] disconnect

**Comment by naddaf** [comment]
Is this log related to a sender that wants to start an application (i.e. the same app is not yet running on the receiver) and then it practically succeeds in launching the app on the receiver but still due to network issues it *thinks* it didn't succeed and onApplicationConnectionFailed() is fired and then it recovers the connectivity? Is this the correct sequence of events?

**Comment by ChadMcQuillen** [comment]
Yes, that is correct.

**Comment by naddaf** [comment]
Ok. Then when it "recovers", is everything looking right?

**Comment by ChadMcQuillen** [comment]
No.  Since onApplicationConnectionFailed() gets called during that process I do not then ever see a successful onApplicationConnected() message.  If I were to try and call sendDataMessage() I would get a 'NoConnectionException'.

**Comment by naddaf** [comment]
Please add the following to your DataCastManager and see if that is enough for recovering the data channels that you had previously set up:

   @Override
    public void onConnectivityRecovered() {
        try {
            attachDataChannels();
        } catch (IOException | IllegalStateException e) {
            LOGE(TAG, "onConnectivityRecovered() Failed to reattach data channels", e);
        }
        super.onConnectivityRecovered();
    }

**Comment by ChadMcQuillen** [comment]
OK... here is what I found.  When I first tried your change the chromecast had an even more intermittent connection because load times were extended even longer.  The first couple times I tried it I *think* I got a NoConnectionException caught in your code above where it attempted to attachDataChannels().  The connectivity of the chromecast was so bad that it recommended that I use the HDMI extender (first time I had ever seen that message).  So, I gave that a whirl and things are *much* better.  None of the errors I had seen previously had occurred.  I took the extender back off to try and re-create, and I saw my prior problems (onApplicationConnectionFailed()), but it went down a slightly different code path before and I did not see your code attempt to execute.  The debug I saw in that case was as follows:

`08-30 14:40:33.167    3347-3347/com.bannerstonesoftware.XYZ D/ccl_BaseCastManager﹕ [v2.3.2] onConnectionFailed() reached, error code: 7, reason: ConnectionResult{statusCode=NETWORK_ERROR, resolution=null}
`

Having gone all through that though...  If the above code worked then would we not be in an inconsistent state with the cast icon (per the fix in #203)?

**Comment by naddaf** [comment]
The change suggested above only tries to make sure that the data channels are set up after you receive a recovery message and is independent of the other fix. The HDMI extender is useful when there is plenty of interference from your TV that can cause issues for chromecast so by using an extender, you are putting some distance in between your TV and chromecast and that reduces the interference. So with the extender, it seems you are not seeing any issues. When there is plenty of interference like what you were experiencing, it is very difficult to get around connection issues. When the SDK observes a network issue, it calls the onConnectionSuspended() and then tries to reconnect and that is what you were observing. I will checkin the change made in the other issue. As for this one, a bit more testing is needed before I feel comfortable checking it in. If with extender everything is fine for you, then you might want to try the following (with the extender): connect and launch your app. then after a short while, quickly turn off wifi and turn it back on and see what happens.

**Comment by ChadMcQuillen** [comment]
Yes, that works (post-launch of the receiver).  Without the change I would stop receiving updates from the receiver.  With the change communication gets restored.  The receiver is launching too quickly now for me to try to see what the behavior would be during launch.

**Comment by naddaf** [comment]
Great, so that new change is doing what it is supposed to do as well. I am also glad the extender is fixing the interference issue for you. I will keep this (and the other issue) open till I checkin my changes and will close them then. Thanks for working with me to test these changes.

**Comment by ChadMcQuillen** [comment]
No problem.  Thanks for the super quick turn-around time.

**Comment by naddaf** [comment]
Addressed in 2.4
