### ISSUE TITLE
Crash onRouteSelected after filtering devices

### ISSUE THREAD

**Issue by jegumi** [googlecast/CastCompanionLibrary-android#207]
When filtering the category of devices "addControlCategory(MediaControlIntent.XXX)" the app is crashing. 

This happens because a null device is received on the method onRouteSelected  (CastMediaRouterCallback file) for the devices filtered. It must be some timing issue, as I cannot reproduce it in debug mode, but it happens 100% in a normal execution.

The crash is on the line 58 of CastMediaRouterCallback.java
LOGD(TAG, "onRouteSelected: mSelectedDevice=" + device.getFriendlyName());

**Comment by naddaf** [comment]
CCL is assuming you are just dealing with cast devices. Is the device you are selecting a non-cast device? Why have you changed  the addControlCategory from:
addControlCategory(CastMediaControlIntent.categoryForCast(mApplicationId))?

**Comment by naddaf** [comment]
Closed due to lack of response
