### ISSUE TITLE
problem with FetchBitmapTask

### ISSUE THREAD

**Issue by Kening** [googlecast/CastCompanionLibrary-android#209]
I am getting a crash in the onPostExecute() call of FetchBitmapTask, and the mMediaSessionCompat object is null (maybe the clearMediaSession is called while the asynctask is working?). so the onPoseExecute call will need to make sure the media session is not cleared.

**Comment by naddaf** [comment]
If you want to report an issue, please provide:
1. Stack Trace
2. Steps to reproduce
3. Exact application you used; I would prefer to see the repro steps with CastVideos, if possible, so I have the source
