### ISSUE TITLE
having cast buttons on multiple activities

### ISSUE THREAD

**Issue by Kening** [googlecast/CastCompanionLibrary-android#210]
I have multiple activities in my app, all activities require a cast button in the UI.

the problem is that if I register a cast consumer in each activity, only the first activity will get its onCastAvailabilityChanged called. As a result, I am only able to detect cast availability on the first activity.

I think this may be a problem not in the library but with the media router API, 

http://stackoverflow.com/questions/19722961/chromecast-with-multiple-activity

**Comment by naddaf** [comment]
at the start up of any activity, you can use VideCastManager.isRouteAvailable(0 and then use that callback
