### ISSUE TITLE
Connection is NOT automatically resumed when disabling and re-enabling network

### ISSUE THREAD

**Issue by BigXiaoYang** [googlecast/CastCompanionLibrary-android#212]
STEPS:
1. connect to cast receiver.
2. disable phone device network. (cast button will be in connecting state, but failed,  and then cast button will be in disconnecting state)
3. re-enable the phone device network.

ACTUAL RESULT:
The connection is not automatically resumed.
The connection can be manually recovered.

EXPECTED RESULT:
The connection should be automatically resumed when re-enable the network while casting. So, the state of the app should be the same as before disabling network.
See https://developers.google.com/cast/docs/design_checklist#sender-control-resume

reproduce rate:
100%

**Comment by naddaf** [comment]
Please turn on debugging in CCL (in LogUtils, set DEBUG to true) and create and attach a log starting from the time that you disconnect network.

**Comment by BigXiaoYang** [comment]
Hi, I uploaded the log to the link below. (CCL 2.4, Nexus5 5.1.1)
https://gist.github.com/BigXiaoYang/c7036cb0f02e630e1fea

**Comment by naddaf** [comment]
Debugging for CCL was mot turned on, I do mot see any "ccl_**" entry in the log

**Comment by BigXiaoYang** [comment]
sorry for that, I updated new log to below 
https://gist.github.com/BigXiaoYang/dfbd9f22aad355a33822

**Comment by naddaf** [comment]
What application are you using?

**Comment by BigXiaoYang** [comment]
your cast-videos demo
https://github.com/googlecast/CastVideos-android

**Comment by naddaf** [comment]
after you connect, start casting a video and then disable -> enable wifi and see if that works or not.

**Comment by BigXiaoYang** [comment]
looks like it works correctly while there is video casting. app reconnected to receiver after enabled network.

**Comment by naddaf** [comment]
that is the intended behavior.
