### ISSUE TITLE
Feature Request: Please add functionality for LaunchOptions

### ISSUE THREAD

**Issue by drecrabb** [googlecast/CastCompanionLibrary-android#213]
At BaseCastManager:983

Please change:
`Cast.CastApi.launchApplication (GoogleApiClient client, String applicationId)`
to:
`Cast.CastApi.launchApplication (GoogleApiClient client, String applicationId, LaunchOptions launchOptions)`
and add ability to set `launchOptions`.

Not providing LaunchOptions causes undesired behavior as our app used to rely on calling the following directly, setting `relaunchIfRunning` to true:
`Cast.CastApi.launchApplication (GoogleApiClient client, String applicationId, boolean relaunchIfRunning)`
which is no longer possible in the CCL.

Cheers,
André

**Comment by naddaf** [comment]
LaunchOptions is related to the application launch, so I am not sure why loadMedia should have anything to do with the LaunchOptions, can you explain?

**Comment by drecrabb** [comment]
loadMedia is what calls down to launch the application, as the CCL doesn't provide a launch feature.

Providing the LaunchOption to relaunchIfRunning should relaunch the application at every call to loadMedia (unless joining) since launchApplication gets called.
The options wouldn't have to be specified in every call to loadMedia, they could perhaps be set after initialization. But currently the CCL doesn't support them at all.

**Comment by naddaf** [comment]
That is not quite correct. loadMedia is not responsible for launching app at all; when you connect to a cast device, application is launched on the receiver, and at that time there is no media involved. In fact, the launch option that you are referring to is related to just how the app is launched and no matter what options you set there, loading a new media is not going to cause a relaunch of the app; as long as the app is still running and an active session is up, loading a new media is not going to do anything but loading a new media within that existing session.

**Comment by drecrabb** [comment]
Ah it seems I had confused the code paths. Yes its the call to onDeviceSelected that will eventually launch the app. This would be a more logical place to provide the LaunchOptions functionality.

**Comment by naddaf** [comment]
The proper place for having such an option is during or shortly after initializing the Cast Manager, so I may add that there. Since it is only for launch process, that option doesn't need to be persisted either.

**Comment by drecrabb** [comment]
Sounds great :)
