### ISSUE TITLE
Application crashes when video ends while casting on Chromecast device

### ISSUE THREAD

**Issue by softvision-mariusduna** [googlecast/CastCompanionLibrary-android#215]
Steps to reproduce:
1. Connect Android device to the router.
2. Tap `Cast` button and select `Chromecast` device from the list.
3. Play a mp4 video and observe behaviour when videos ends.
Application that uses Chromecast SDK crashes.

Note to Cast SDK devs:
It would be very helpful to have the possibility to managed/overwrite the behavior of "BaseCastManager.checkConnectivity()" method by extending the CastManager(specially for VideoCastManager) . Currently this method is "public final".

I'm asking this because the above method is used in various scenarios/places inside VideoCastManager.class, and causes unwanted crashes.

Or at least catch the exceptions it throws inside Cast SDK, where the method call is used, and handle the cast states in a friendly way, instead of having the exceptions bubble up for any involved cast states.

Current behavior is also causing a lot of troubles if you try to add/integrate, in parallel, custom cast support for other cast devices. 

![screen shot 2015-09-15 at 16 59 02](https://cloud.githubusercontent.com/assets/11609591/9878411/2cddee80-5bcb-11e5-8985-24cc75eef4c9.png)
![screen shot 2015-09-15 at 16 58 14](https://cloud.githubusercontent.com/assets/11609591/9878410/2cd74832-5bcb-11e5-848c-6f8f49f525a2.png)
![screen shot 2015-09-15 at 16 59 25](https://cloud.githubusercontent.com/assets/11609591/9878412/2ce118c6-5bcb-11e5-830c-ae8f2d76dc20.png)

**Comment by naddaf** [comment]
Please try the latest version of the library; yours is 2.2 and I believe the issue you are running into was fixed in 2.4
