### ISSUE TITLE
Layout in landscape mode

### ISSUE THREAD

**Issue by softvision-octaviancudalbu** [googlecast/CastCompanionLibrary-android#216]
Description of the issue:

1.Extend VideoCastControllerActivity
2.By doing so, our extended activity will already have the layout established in cast_activity.xml by the VideoCastControllerActivity.onCreate(...) {
......
setContentView(R.layout.cast_activity);
......
}
3.The above mentioned layout file has 2 versions located in "layout" and "layout-land" folders, so when rotating any device in landscape mode, it will use the second layout, which is different than the one in portrait mode. This second layout is not on the liking of many users, but unfortunately we cannot change it's appearance

My request for you is to either implement the same layout as in portrait mode, or give us a way to implement our own layout
The application in which we implemented the library is on the Android platform,
My Gradle build configs used for testing are:

minSdkVersion 14
targetSdkVersion 22 

    compile 'com.android.support:support-v4:22.2.1'
    compile 'com.android.support:mediarouter-v7:22.2.1'
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.google.android.gms:play-services-base:7.5.0'
    compile 'com.google.android.gms:play-services-analytics:7.5.0'
    compile 'com.google.android.gms:play-services-cast:7.5.0'

I have attached 2 screenshots in which can be observed the 2 different layouts

Thank you

![layout_land](https://cloud.githubusercontent.com/assets/11849476/9904895/1829e524-5c8a-11e5-9fe3-36dc2baf7dc6.JPG)
![layout_portrait](https://cloud.githubusercontent.com/assets/11849476/9904894/1828eeee-5c8a-11e5-845c-703dbc0ebb0d.JPG)

**Comment by firekesti** [comment]
Hi, I'm not with the project, but generally speaking, you can override library resources by duplicating them. 

If you make a resource in your own layout-land folder called cast_activity, it will override the one that comes with the library. Just make sure you include all the same elements with the same IDs so the click listeners work. Then just rearrange them to your liking. Hope this helps!

**Comment by naddaf** [comment]
As was mentioned by Kate, just define your own layout resource in landscape or portrait mode and call them cast_activity and do as you wish.

**Comment by softvision-octaviancudalbu** [comment]
Thank you for responses, the solution does work

But we did not want to create a separate layout on our side, we only wanted to be able to force the same layout for landscape mode as in portrait mode, following the same design in the library
The reason for this is that if this library changes the portrait layout in any future releases, we would have to manually change the same layout for landscape mode and we wanted to keep the local dependencies as low as possible

Thanks again
