### ISSUE TITLE
Media route chooser dialog UI is defferent than checklist

### ISSUE THREAD

**Issue by BigXiaoYang** [googlecast/CastCompanionLibrary-android#217]
- checklist (https://developers.google.com/cast/docs/design_checklist#sender-cast-menu-connected)
![sender-cast-menu-connected1_a](https://cloud.githubusercontent.com/assets/5369879/9924664/384523f0-5d34-11e5-876e-db90f3d8c1c9.jpg)

- cast-videos demo app:
![device-2015-09-17-113824](https://cloud.githubusercontent.com/assets/5369879/9925441/2b72e298-5d3e-11e5-9951-52f7c4edeafa.png)
    - no cast button on title bar left
    - the text "No media information available" should be "Ready to cast videos from this app".
    - "STOP CASTING" button should be "Disconnect"

**Comment by naddaf** [comment]
Differences are due to the recent changes in the Media Router library.

**Comment by BigXiaoYang** [comment]
I meant the difference of the "no info" text and button text. 
and I found they are defined in the class "VideoMediaRouteControllerDialog" which is in CCL library.

**Comment by naddaf** [comment]
The phrase "Stop Casting" is not defined in CCL, it is part of the Media Router library. That "content" of the dialog is defined in the CCL not the button. As for the wording when there is no media, the UX checklist doesn't dictate the wording, so CCL can change that and in fact, any application can override the appropriate resource to override that.

**Comment by BigXiaoYang** [comment]
ok, thanks
