### ISSUE TITLE
MiniController - Pause/Play icon incorrectly displayed for livestream

### ISSUE THREAD

**Issue by jonasao** [googlecast/CastCompanionLibrary-android#218]
I am casting a stream of type MediaInfo.STREAM_TYPE_LIVE. When pausing/stopping the stream by clicking on the stop icon in the MiniController, the command is correctly sent to the Chromecast, and the stream is stopped, and the icon changes to a play icon. To resume playback of the stream, I click the play icon in the MiniController, but nothing happens, and the play icon is left there with a spinner surrounding it.

The problem lies in the method VideoCastManager.onPlayPauseClicked(View v), where it seems to me that the live-stream triggers the wrong MediaStatus when the pause icon is clicked.

This is the original version of the method:
```java
@Override
    public void onPlayPauseClicked(View v) throws CastException,
            TransientNetworkDisconnectionException, NoConnectionException {
        checkConnectivity();
        if (mState == MediaStatus.PLAYER_STATE_PLAYING) {
            pause();
        } else {
            boolean isLive = isRemoteStreamLive();

            if ((mState == MediaStatus.PLAYER_STATE_PAUSED && !isLive)
                    || (mState == MediaStatus.PLAYER_STATE_IDLE && isLive)) {
                play();
            }
        }
    }
```

A working version of the method:
```java
@Override
    public void onPlayPauseClicked(View v) throws CastException,
            TransientNetworkDisconnectionException, NoConnectionException {
        checkConnectivity();
        if (mState == MediaStatus.PLAYER_STATE_PLAYING) {
            pause();
        } else {
            boolean isLive = isRemoteStreamLive();
            if (mState == MediaStatus.PLAYER_STATE_PAUSED) {
                play();
            }
        }
    }
```

The code incorrectly reports the MediaStatus (mState) = MediaStatus.PLAYER_STATE_PAUSED, even for livestreams (MediaInfo.STREAM_TYPE_LIVE), this is why this method fails. The MediaStatus (mState) does never get the value MediaStatus.PLAYER_STATE_IDLE...

**Comment by naddaf** [comment]
For a live stream, it is up to your receiver to provide the correct status when it is "paused"; we do not have a DVR functionality so "pause" is in fact a wrong state for a live stream in this case since we are not really pausing the stream and if user was to continue (un-pause), it would pick up from the current time and not the previous position. As such, CCL assumes that when you "pause" a stream, you are really "stopping" it and expects the receiver to report IDLE state.

**Comment by homburg** [comment]
For others trying to use the CastReferencePlayer and CastCompanionLibrary on android, see this patch:  https://github.com/googlecast/CastReferencePlayer/pull/23/files
