### ISSUE TITLE
Cast button doesn't animates while connecting

### ISSUE THREAD

**Issue by BigXiaoYang** [googlecast/CastCompanionLibrary-android#220]
Cast button doesn't animates while connecting
checklist: https://developers.google.com/cast/docs/design_checklist#sender-cast-icon-states

Step:
1. launch app
2. click cast button
3. select one receiver device.

Actual result:
the cast button will become to connected states immediately

Expected result:
cast button animates while connecting. and become to connected states after connected.

Device: Nexus 5 (Android 5.1.1), Nexus 6 (Android 5.1.1)
App: CastVideos-android demo app (2.3.1), CCL (2.4)

**Comment by jonasao** [comment]
Device: Sony Xperia Z1 (Android 5.1.1)

Cast button animates, but it is nearly invisible, because the connection is established in such short amount of time. Could this be the case for you to? @BigXiaoYang

**Comment by BigXiaoYang** [comment]
Maybe you are right, I disable the network while connecting. cast will try to reconnect, then cast button animates. thanks
