### ISSUE TITLE
IllegalStateException thrown

### ISSUE THREAD

**Issue by jonasao** [googlecast/CastCompanionLibrary-android#221]
After connecting to a Chromecast device, and attempting to start playback, a java.lang.IllegalStateException is thrown:

```java
java.lang.IllegalStateException: 
This Activity already has an action bar supplied by the window decor. 
Do not request Window.FEATURE_ACTION_BAR and set 
windowActionBar to false in your theme to use a Toolbar instead.
```

A simple fix to this exception is to alter the method VideoCastControllerActivity.setupActionBar(), making this handle an existing ActionBar object:
```java
private void setUpActionBar() {
        mToolbar = (Toolbar) findViewById(R.id.toolbar);

        // HACK: Avoid java.lang.IllegalStateException if an action bar already exists.
        if (getSupportActionBar() != null)
            return;

        setSupportActionBar(mToolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
    }
```

**Comment by naddaf** [comment]
VideoCastControllerActivity doesn't have an action bar, it has a tool bar (based on its layout) so I am not sure what you are doing there.

**Comment by jonasao** [comment]
My "MainActivity" class inherits from "ActionBarActivity", as the documentation describes. (Even though the "ActionBarActivity" is deprecated and "AppCompatActivity" is suggested instead.) My application's theme is set to "Theme.AppCompat". 

In MainActivity.onCreate(), the VideoCastManager is initialized:
```java
...
VideoCastManager.initialize(this, CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID, null, null)
                .enableFeatures(VideoCastManager.FEATURE_NOTIFICATION |
                        VideoCastManager.FEATURE_LOCKSCREEN |
                        VideoCastManager.FEATURE_WIFI_RECONNECT |
                        VideoCastManager.FEATURE_DEBUGGING);

mCastManager = VideoCastManager.getInstance();

// adding minicontroller
...
// adding videocastconsumer
...
```

When my application discovers that there are available Chromecast devices nearby, the cast icon appears correctly in the top right corner. By clicking this and selecting an appropriate Chromecast device from the list of devices, opens a connection to the selected device.

Once the connection is established, a "Play" button is displayed in the main GUI of the application, allowing the user to start playback. When the huser clicks the "Play" button, a method, creating MediaMetadata and MediaInfo objects and calling mCastManager.startVideoCastControllerActivity(...) is called.

```java
...
Bundle bundles = com.google.android.libraries.cast.companionlibrary.utils.Utils.mediaInfoToBundle(mediaInfo);

mCastManager.startVideoCastControllerActivity(getApplicationContext(), bundles, 0, true);
...
```

This leads to the java.lang.IllegalStateException being thrown, when attempting to render the VideoCastControllerActivity screen.

Do you have any other suggestions on how to avoid this problem?

**Comment by naddaf** [comment]
I am in the process of updating the documentation; everything now should use AppCompatActivity and not the deprecated ActionBarActivity. The VideoCastControllerActivity, if you look at the code, is already using AppCompatActivity and a toolbar,  the theme set for that should reflect that. For example, in CastVideos-android app that uses this library, in its manifest, it uses a theme (CastVideosDark)  for VideCastControllerActivity that has no action bar:

    <style name="Theme.CastVideosDark" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimaryDark">@color/black</item>
    </style>

You may need to do the same as well (at least for that activity, if not the ret of your application.
