### ISSUE TITLE
Listeners for mSkipNext and mSkipPrevious buttons

### ISSUE THREAD

**Issue by softvision-octaviancudalbu** [googlecast/CastCompanionLibrary-android#225]
Hi,

We have an application that extends VideoCastControllerActivity from your library and we want to use the same layout as the library provided

The issue we are experiencing:
- connect to Chromecast, then tap on either "next" or "previous" button
- although the logic implemented in the library is correct and a loading bar is presented to the user when Chromecast sends us an event that data is currently loading, there's a certain delay involved of approximately 2-3 seconds. During this time frame the user does not have any feedback from the app.

We would kindly ask you to display the loading bar sooner (just when the user taps), or at least provide us with a way of also receiving the "tap event" so we can at least present a Toast message or some other form of UI indication (maybe a selector for the buttons ...)
Right now the listeners are added to the "mSkipNext" and "mSkipPrevious" buttons in VideoCastControllerActivity.loadAndSetupViews()

Thank you

**Comment by naddaf** [comment]
Will try to add that.

**Comment by naddaf** [comment]
Please check out v2.5 and see if that gives you the visual feedback you needed.
