### ISSUE TITLE
Volume control hardware buttons don't adjust the volume when sender is locked

### ISSUE THREAD

**Issue by BigXiaoYang** [googlecast/CastCompanionLibrary-android#226]
Action Performed:
1. Launch the app
2. Connect to cast receiver
3. Cast any content
4. Lock device
5. Tap on device ""Home"" button
6. Push device volume control buttons

Expected Result:
Volume control hardware buttons should adjust the volume on the sender app when the phone is locked.

Actual Result:
Volume control hardware buttons don't adjust the volume on the sender app when the phone is locked.

Additional Information:
Bug repeatable: 5/5
Test Case #
App: CastVideos-android demo app (version 2.3.1), CCL (2.4) 
Device: Samsung Galaxy S5(OS: 4.4.2),  Samsung Tablet GT-P5210(OS: 4.4.2)

**NOTE: NOT reproduced on Nexus5(Android 5.1.1)**

**Comment by naddaf** [comment]
This is due to the changes that Samsung has made to its build and there is nothing that this library can do about it.
