### ISSUE TITLE
VideoCastManager.initialize or VideoCastManager.getInstance

### ISSUE THREAD

**Issue by softvision-octaviancudalbu** [googlecast/CastCompanionLibrary-android#227]
Hi, 

We are experiencing a series of issues with this library:

One being when connected to Chromecast, we are casting a media item and during this streaming process we physically disconnect the Chromecast device from TV.
After removal, the casting icon in VideoCastControllerActivity does not inform us of the disconnecting event (it is still in "connected state"), even more, I attached the debugger and checked the state of BaseCastManager.isConnected() and it returned "True".

This leads to the following question: how should we appropriately use "VideoCastManager.getInstance()", because this will throw an exception if there isn't a connection and ONLY if you know it is initialized it will return that instance. Would it be ok if we use "VideoCastManager.initialize(...)" instead, every time we need to get the instance of "VideoCastManager"?  Please clarify usage scenarios for both methods. 

Thank you in advance.

I also think the following logs snippet extracted from our app Crashlytics reports would be helpful for these kind of scenarios:

```
"java.lang.NullPointerException
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$29.onPostExecute(VideoCastManager.java:2271)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$29.onPostExecute(VideoCastManager.java:2268)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)"
```

**Comment by naddaf** [comment]
I am not able to reproduce this. Here are the steps I took;
- Launched CastVideos-android app
- Started casting a video
- Navigated to the full screen VideoCastControllerActivity
- Disconnected my chromecast

Then the cast icon first showed suspended state and then it disconnected and that activity was closed. In the main activity of CastVideos app, the cast icon showed as disconnected.

Are you following a different set of steps?

**Comment by softvision-octaviancudalbu** [comment]
Hi, 

In our setup from yesterday it was fairly easy to reproduce, this occurred several times
Today is not so easy to reproduce, but we are working on a scenario to better explain what exactly is the cause
But can you please clarify for me the question I have addressed in the topic name of this issue, which is: What is the best practice for using "VideoCastManager.initialize()" or "VideoCastManager.getInstance", because in the scenario where some error occurred and we try to get the instance of VideoCastManager with getInstance() method, it would throw an exception if this instance does not exist
But using "VideoCastManager.initialize()" still returns the instance if it already exists, and if not, it will try to create one

Should we using like this:
try {
   VideoCastManager manager = VideoCastManager.getInstance();
} catch (IllegalStateException e) {
   VideoCastManager manager = VideoCastManager.initialize();
}

**Comment by naddaf** [comment]
No, initialization should happen once in the Application instance and from that point on, the manager singleton should be accessible throughout your app by using getInstance(). Are you using an application with activities running in different processes? If not, then you need to see what you are doing wrong in your app; any piece of your application, when run, would need an Application instance and if you are initializing the cast manager in the onCreate() of your application, that guarantees that this singleton is available ahead of any other piece of code in your app (activities, services, etc).

**Comment by parthpatibandha** [comment]
Hello sir, i develop receiver application on cast developer account with two app id (cast key getting from management). But now i am able to only cast video from one key and cast audio from another key Now i want to cast both from single key. 
1. Can i able to initialize VideoCastManager twice with different key ?
2. Is that any setting missing by management so thats why single key not working for both video and audio ?
Thanks

**Comment by naddaf** [comment]
You should not use a closed issue to ask a different question.
