### ISSUE TITLE
Artifacts for integrating CCL

### ISSUE THREAD

**Issue by PhatJo** [googlecast/CastCompanionLibrary-android#229]
I'm having problems integrating this library *and* sharing it with the rest of my team. I followed the setup instructions indicated in the CastVideos-android project by cloning into a directory just one level above my project. Studio reports this problem:

Error:(55, 0) Project with path '..:CastCompanionLibrary' could not be found in project ':Daedalus'.
<a href="openFile:/Users/baba/dev/daedalus/Daedalus_Android/Daedalus/build.gradle">Open File</a>

Even if the build were to succeed, I would have no way of sharing the integrated project as the CCL folder is outside of my project/repo.

So I tried cloning into the repo instead (same directory level as my project), like this:

`/Users/baba/dev/daedalus/Daedalus_Android/<my project files>
/Users/baba/dev/daedalus/Daedalus_Android/CastClientCompanionLibrary`

The CCL turns up as an empty folder on github. 

Instead of cloning the folder, can you publish the gradle artifacts on mavecentral or similar repositories?

**Comment by naddaf** [comment]
If you follow the instructions that are given in the readme file for CastVideos-android app, you should be able to CCL parallel to your own project (as siblings). To share that with your team, I presume you don't need to have CCL in your own repo (assuming you are not going to change it) in which case your team members can follow the same pattern. If you do want to make changes to that, it is better to have it as a separate entity/project in your own repo anyways to keep things fully independent and be able to merge down changes from GitHub.

**Comment by naddaf** [comment]
In addition, you can always build an AAR from CCL (./gradlew build) and the use that AAR in your own project.

**Comment by PhatJo** [comment]
> If you do want to make changes to that, it is better to have it as a separate entity/project in your own repo anyways to keep things fully independent

We don't plan to make changes per se, but rather that we like to maintain a self-contained project without creating dependencies on local dev machine configuration (i.e., asking each contributor to setup the CCL folder = duplicate efforts). 

In any case, how would we set the CCL project as a separate entity within our Daedalus project... as a git submodule? What I tried before -- clone CCL into our repo (as a child of Daedalus) isn't working as committing the CCL folder leads to an empty folder showing up on github. Besides, it makes Android Studio go into a weird mode where the Run/Debug buttons are greyed out

**Comment by PhatJo** [comment]
I'm curious, why have you not made a maven/bintray/etc distribution for this project? It's a very helpful library for sure, but it'd be even more easier and faster if all it took were a single line of gradle compile

**Comment by naddaf** [comment]
The reason for not having that as an aar in a maven repo is mainly around the signing process; I do not want to start distributing this in AAR format through a maven repo unless it is signed with an official key issues by Google;  it is something that is on my todo list but is more involved than it may sound.

**Comment by naddaf** [comment]
Regarding your main question, why don't you follow the earlier recommendation of creating an AAR yourself and then using that across your project(s)?

**Comment by PhatJo** [comment]
I haven't had success yet when using a locally generated AAR. I cloned CCL into a sibling directory of my main project and ran `./gradlew build` inside it. Then I tried the following 2 different methods of integrating the AAR:
### method 1: use libs folder ###
1. Add debug & release AARs into my app's 'libs' folder
2. In app's build.gradle:

    `compile (name: 'CastCompanionLibrary-debug', ext: 'aar')`
    `compile (name: 'CastCompanionLibrary-release', ext: 'aar')`
http://stackoverflow.com/a/21890937/1145905

### method 2: add CCL as module(s) ###
1. File -> New Module -> Import .JAR/.AAR. Import both debug & release versions as separate modules
2. app's build.gradle:

`compile (':CastCompanionLibrary-debug')`
`compile (':CastCompanionLibrary-release')`
http://stackoverflow.com/a/24894387/1145905

In both cases, it looks like I have to force disable the unique package name directive as Studio complains about two libraries having the package name "com.google.android.libraries.cast.companionlibrary" with `android.enforceUniquePackageName = false`. Not exactly ideal

In both cases, the compilation seems to fail as the IDE still doesn't find the CCL classes:
![screen shot 2015-09-28 at 5 29 48 pm](https://cloud.githubusercontent.com/assets/1447912/10152737/35277900-660a-11e5-869b-ba3db84cbbee.png)

**Comment by naddaf** [comment]
Here is what I just did to have CastVideos-android app to work with CCL in aar format:
* Build CastCompanionLibrary-debug.aar and put in inside the "libs" directory
* Comment out the only line in settings.gradle
* Update build.gradle to change the dependencies to:
```
dependencies {
    compile files('libs/android-query.0.25.10.jar')
    compile 'com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.6.1'
    compile 'com.github.amlcurran.showcaseview:ShowCaseLibrary@aar'
    compile 'com.google.android.libraries.cast.companionlibrary:CastCompanionLibrary-debug@aar'
    compile 'com.android.support:appcompat-v7:22.2.+'
    compile 'com.android.support:mediarouter-v7:22.2.+'
    compile 'com.google.android.gms:play-services-cast:8.1.+'
}
```
* Make sure "libs" directory is part of your repository (should already be in CastVideos app):
```
repositories {
    jcenter()
    flatDir {
        dirs 'libs'
    }
}
```
That is all I needed to do. I hope you can adapt this to your project.

**Comment by PhatJo** [comment]
I tried to adapt this to my project, but unfortunately nothing has changed. My settings.gradle file is intact. I have CastCompanionLibrary-debug and -release.aar inside 'libs'. 

This is the relevant portion of my build.gradle:
![screen shot 2015-09-28 at 6 53 01 pm](https://cloud.githubusercontent.com/assets/1447912/10153546/3430ee84-6612-11e5-9b74-2410b81546ce.png)

**Comment by PhatJo** [comment]
@naddaf , I went ahead and forked the ref project to see if your proposed changes worked on my setup: https://github.com/PhatJo/CastVideos-android
With the 'libs' way of importing the aars, the forked project fails to compile with 2 errors:
`Error:(43, 28) No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version')`. (looks like manifest file merge problem), and

`Error:Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/baba/dev/android/sdk/build-tools/23.0.0/aapt'' finished with non-zero exit value 1`

I'm using Android Studio 1.4 RC2 on Mac OS X 10.10.2

**Comment by naddaf** [comment]
Do you have play service 8.1 installed? As I said, I did a fresh clone of the two projects (CCL and CastVideos) and built the aar and dropped it in libs dir of the CastVideos. Here is the diffs:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   build.gradle
	modified:   settings.gradle

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	libs/CastCompanionLibrary-debug.aar

no changes added to commit (use "git add" and/or "git commit -a")
```
And diffs:
```
$ git diff
diff --git a/build.gradle b/build.gradle
index 66e6f76..79977f9 100644
--- a/build.gradle
+++ b/build.gradle
@@ -58,8 +58,12 @@ dependencies {
     compile files('libs/android-query.0.25.10.jar')
     // to get around https://code.google.com/p/android/issues/detail?id=52962, we need to
     // depend on both debug and release versions of the library
-    releaseCompile project(path: '..:CastCompanionLibrary', configuration: 'release')
-    debugCompile project(path: '..:CastCompanionLibrary', configuration: 'debug')
-    compile 'com.github.amlcurran.showcaseview:ShowCaseLibrary@aar'
+    //releaseCompile project(path: '..:CastCompanionLibrary', configuration: 'release')
+    //debugCompile project(path: '..:CastCompanionLibrary', configuration: 'debug')
     compile 'com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.6.1'
+    compile 'com.github.amlcurran.showcaseview:ShowCaseLibrary@aar'
+    compile 'com.google.android.libraries.cast.companionlibrary:CastCompanionLibrary-debug@aar'
+    compile 'com.android.support:appcompat-v7:22.2.+'
+    compile 'com.android.support:mediarouter-v7:22.2.+'
+    compile 'com.google.android.gms:play-services-cast:8.1.+'
 }
diff --git a/settings.gradle b/settings.gradle
index 088e8ed..c04838a 100644
--- a/settings.gradle
+++ b/settings.gradle
@@ -13,4 +13,3 @@
  * See the License for the specific language governing permissions and
  * limitations under the License.
  */
-include '..:CastCompanionLibrary'
```
and I can successfully build CastVideos app with this structure and set up.

You need to resolve your issues on how to properly use the aar file yourself, there isn't much more I can do to help you with your project. You might want to try using command line gradle commands first to avoid running into issues with Android Studio set up, if any.

**Comment by naddaf** [comment]
And, btw, I don't see you including play services for cast; in fact you don't need to include base, but you DO need to include cast:
compile 'com.google.android.gms:play-services-cast:8.1.+'

**Comment by PhatJo** [comment]
There we go, the key was the missing cast directive. It hadn't occurred to me that library AARs do not propagate their dependencies up towards the app module. 
Thanks for creating this library and your help!
