### ISSUE TITLE
System.UI crash on Samsung Galaxy Tab Android 4.4.2

### ISSUE THREAD

**Issue by Appostrophe** [googlecast/CastCompanionLibrary-android#230]
Launch the app on the Samsung Galaxy Tab 4 8"
Connect to a chromecast.
Cast any content.
During casting press the home button.
Swipe from the top of the Tab 4's home page down (for menu/options).
Notice that the System UI repeatedly crashes.

**Comment by Appostrophe** [comment]
Here is the crash log:

>09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.media.IAudioService$Stub$Proxy.getStreamMaxVolume(IAudioService.java:1261)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.media.AudioManager.getStreamMaxVolume(AudioManager.java:879)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at com.android.systemui.statusbar.policy.VolumePanel.getStreamMaxVolume(VolumePanel.java:192)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at com.android.systemui.statusbar.policy.VolumePanel.updateVolume(VolumePanel.java:132)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at com.android.systemui.statusbar.policy.VolumePanel.onBarExpand(VolumePanel.java:236)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeExpandedVisible(PhoneStatusBar.java:2049)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at com.android.systemui.statusbar.phone.PhoneStatusBarView.onPanelPeeked(PhoneStatusBarView.java:199)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at com.android.systemui.statusbar.phone.PanelBar.panelExpansionChanged(PanelBar.java:178)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at com.android.systemui.statusbar.phone.PhoneStatusBarView.panelExpansionChanged(PhoneStatusBarView.java:269)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at com.android.systemui.statusbar.phone.PanelView.setExpandedHeight(PanelView.java:598)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.animation.PropertyValuesHolder.nCallFloatMethod(Native Method)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.animation.PropertyValuesHolder.access$400(PropertyValuesHolder.java:35)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:962)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:571)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1175)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1216)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:637)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.view.Choreographer.doFrame(Choreographer.java:572)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.os.Handler.handleCallback(Handler.java:733)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.os.Looper.loop(Looper.java:157)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at android.app.ActivityThread.main(ActivityThread.java:5341)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at java.lang.reflect.Method.invoke(Method.java:515)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1259)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
09-30 08:33:04.295: E/AndroidRuntime(2890): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by Appostrophe** [comment]
Here is the thread on this issue tracked on the Android project
https://code.google.com/p/android/issues/detail?id=70783

**Comment by naddaf** [comment]
I don't have any reason to believe that this is related to CCL; see https://plus.sandbox.google.com/+Anoopgolden/posts/VbZzmLC1S1c as well. Do you have a reason to believe this is casused by CCL?

**Comment by Appostrophe** [comment]
No I don't. As a matter of fact I know this is OEM issue and not even an Android issue.
