### ISSUE TITLE
Receiver application not launched

### ISSUE THREAD

**Issue by thomasfriedl** [googlecast/CastCompanionLibrary-android#231]
I noticed after upgrading to 2.5 that nothing happend after connecting to a chromecast device - meaning no receiver application was launched.

After debugging for some time I found out that it's necessary to call setLaunchOptions on the VideoCastManager - otherwise the launchoptions are null and no application is launched.

This isn't really an issue / bug but I wanted to save other people the trouble to go through everything again.

**Comment by naddaf** [comment]
Thanks for reporting that; the intention was to not force developers to set the LaunchOption and have the previous behavior as the default one but I missed that so I just uploaded an update (2.5.1) that should address that issue; there shouldn't be a need to set the LaunchOption unless a non-default behavior is desired.
