### ISSUE TITLE
Adding several items at once in queue, only keeps the last item

### ISSUE THREAD

**Issue by softvision-octaviancudalbu** [googlecast/CastCompanionLibrary-android#232]
Hello,

We have 2 issues to report regarding Chromecast Queue:
1. We have implemented an application based on Companion library and after several tests performed, came to the conclusion that these issues are library dependent
Also tested the CastVideo Demo application provided by Google and the same behavior occurred
Steps:
- connect to Chromecast
- select several items to be added to queue
You can clearly see on the TV that the selected items are loaded into Chromecast queue, one by one, but no item starts to play until it reaches the last element sent. Then this last element starts to play on TV, but when checking the queue, it only contains itself, as if we were sending only this item at all
We checked the VideoCastConsumerImpl.onMediaQueueUpdated() callback, and is invoked several times, but in the end it contains only 1 element, only the last one.
After this step if you continue to add several more items at once, it does add these items correctly.
This behavior could be also reproduced on the CastVideo Demo by adding several items to queue, one at a time, until the "last" item gets played. After that if you repeat the operation, it correctly adds other items to queue

2. The VideoCastConsumerImpl.onMediaQueueUpdated() callback gets triggered several items, usually 2 times, is this a normal behavior, shouldn't it get called 1 time only, and only when some element(s ) changes ?
Let's say we add 2 items in queue that contains 2 items,  we would receive: 2x callbacks with the list with 3 items and 2x callbacks with the list of 4 items

**Comment by naddaf** [comment]
I need more information on how you are adding items in each steps above, producing some code will help me understand. You also mentioned CastVides app has this issue; that app adds one item at a time so I am not sure exactly how you are adding multiple items at the same time.

**Comment by softvision-octaviancudalbu** [comment]
So, in CastVideo Demo application:
- connect to Chromecast
- tap on "3 dot" menu of any item, select Add to Queue
- tap on "3 dot" menu of another item, select Add to Queue
- tap on "3 dot" menu of another item, select Add to Queue
- tap on "3 dot" menu of another item, select Add to Queue

Observe on the TV that each item is individually loaded
After the last video is loaded, it starts playing
But if you tap Queue icon, you will see that only this item populates the queue, the other items are gone

**Comment by naddaf** [comment]
After you add the very first one, you need to wait till a queue is actually formed and the sender receives that info, otherwise if you add the second item immediately, the receiver will not consider the second item being added to the same queue (since queue hasn't yet formed completely). So to test this, start the first one, then wait long enough to see the mini controller and then start adding subsequent items and see if you get a queue of the items or not.

**Comment by naddaf** [comment]
If you want, you can block the UI till the first one is loaded and then allow the user to add subsequent ones to the queue; that is one easy approach if you want to have that capability. More sophisticated one is to cache the user requests and when a successful load happens, then start adding items from your cache but that can get tricky.

**Comment by softvision-octaviancudalbu** [comment]
Think of the scenario where we use 2 devices connected to Chromecast:
- the first device starts adding 1 item to queue
- simultaneously a second device also wants to add an item to queue
That would mean the second device's operation would fail, as the Queue is not initialized yet

What we need in this case, is a callback that all devices can listen to, to inform us of the Queue status: "INITIALIZING", "INITIALIZED"

**Comment by naddaf** [comment]
This cannot be driven by CCL, so if you need such extensions, you need to file a feature request on the Cast Issue tracker.
