### ISSUE TITLE
How to add more than one item into queue the first time

### ISSUE THREAD

**Issue by softvision-octaviancudalbu** [googlecast/CastCompanionLibrary-android#234]
Hello,

Please help me with the next scenario:
The first time I connect to Chromecast, I need to add several items at once into queue, not just one item at a time
Right now if I send 4 items to queue, only the 4th item remains in queue
How can I do that ?

**Comment by softvision-mariusduna** [comment]
Tha same scenario occured for me too:
 - I connect to the chromecast, the queue is empty no device played before
 - I tried to add several items at once
Only last item is played and the queue shows only the current playing item.

**Comment by naddaf** [comment]
If you want to load multiple items in one shot, just use the current api:
queueLoad(final MediaQueueItem[] items, final int startIndex, final int repeatMode,
            final JSONObject customData)
You can have an array of items loaded in one call to that API
