### ISSUE TITLE
The title bar of route chooser dialog disappeared on Andorid M

### ISSUE THREAD

**Issue by BigXiaoYang** [googlecast/CastCompanionLibrary-android#237]
#### the title bar of route chooser dialog disappeared on Andorid M ####
(only reproduced on Android M)

![device-2015-10-16-165839](https://cloud.githubusercontent.com/assets/5369879/10537927/a17f2c4e-7427-11e5-9d1b-7f6dbcbe300c.png)

app: CastVideos 2.5
library: CCL: 2.5.1
Device: Nexus 5, OS: Android 6.0

**Comment by naddaf** [comment]
The "chooser" dialog is not controlled by CCL and is coming from framework/media router library. In newer version of the support lib, this has changed (although there issues have been introduced, so I don't recommend switching to that yet).
