### ISSUE TITLE
Strange discovery issue

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#238]
I have an app which casts to more than just the Chromecast so I am using the CCL but not the `MediaRouteButton`. For some reason some of my users can't find the Chromecast. I sent them the CastVideos apps compiled with the same CCL I'm using and it finds the Chromecast just fine. So I made a little test app as simple as possible using the CCL and it can't find the Chromecast either. Can you tell me what I'm doing wrong? I'm including in here my test activity code. 

This code below works fine on my test phones. As you can see all it does is initialize the `VideoCastManager`, adds a `VideoCastConsumer`, and calls `startCastDiscovery`. My users having issues don't get a single call back for `onCastDeviceDetected`. 

As a test, I made a change to `BaseCastManager` to use `CALLBACK_FLAG_FORCE_DISCOVERY` and that fixed the issue for those users but I don't understand why? at some point I was told it might have to do with low ram devices but how come CastVideos works just fine for them with the same CCL?

```
 public class MainActivity extends AppCompatActivity {
    private static StringBuilder log = new StringBuilder();
    private TextView textView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        textView = (TextView)findViewById(R.id.log);
        Button button = (Button) findViewById(R.id.sendLog);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent send = new Intent(Intent.ACTION_SENDTO);
                String uriText = "mailto:" + Uri.encode("myemail") +
                        "?subject=" + Uri.encode("Logs") +
                        "&body=" + Uri.encode(log.toString());
                Uri uri = Uri.parse(uriText);

                send.setData(uri);
                startActivity(Intent.createChooser(send, "Send logs..."));
            }
        });
        VideoCastManager manager = VideoCastManager.initialize(getApplicationContext(), CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID, null, null);
        manager.addVideoCastConsumer(new VideoCastConsumerImpl() {
            @Override
            public void onCastDeviceDetected(MediaRouter.RouteInfo info) {
                newLine();

                log("onCastDeviceDetected");
                newLine();
                log(info.toString());
                newLine();

            }

            @Override
            public void onCastAvailabilityChanged(boolean castPresent) {
                newLine();

                log("onCastAvailabilityChanged " + castPresent);
                newLine();


            }
        });
        manager.startCastDiscovery();
    }

    private void log(String msg) {
        log.append(msg);
        textView.setText(textView.getText()+msg);
    }

    private void newLine() {
        log("\n");
    }


}
```

Thanks.

**Comment by naddaf** [comment]
As a test, please do the following: make your "manager" a class variable (and call it, say, mCastManager). Then add the following method to your activity:

boolean isAnyRouteAvailable() {
    MediaRouter router = MediaRouter.getInstance(getApplicationContext());
    return router.isRouteAvailable(mCastManager.getMediaRouteSelector(),
            MediaRouter.AVAILABILITY_FLAG_IGNORE_DEFAULT_ROUTE
                | MediaRouter.AVAILABILITY_FLAG_REQUIRE_MATCH);
}

and then call 
Log.d(TAG, "Is any route available now? " + isAnyRouteAvailable());
right after you do the discovery and see what that prints for those cases that you don't get any callbacks.

**Comment by mntgoat** [comment]
I modified my code to basically do this twice, once as soon as it calls discover and another time after ten seconds. My full code is below again but basically this was the change:

```

....

 mManager.startCastDiscovery();


        log("Is any route available now? " + isAnyRouteAvailable());


        new Handler(Looper.myLooper()).postDelayed(new Runnable() {
            @Override
            public void run() {


                log("Is any route available now (10 secs)? " + isAnyRouteAvailable());
            }
        }, 10000);
```

One of the users already sent me the log and it looked like this:

```
19:04:36 Is any route available now? false

19:04:36 Is any route available now (10 secs)? false
```


Full code:

```package com.castdiscoverytest;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.media.MediaRouter;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import com.google.android.gms.cast.CastMediaControlIntent;
import com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager;
import com.google.android.libraries.cast.companionlibrary.cast.callbacks.VideoCastConsumerImpl;

import java.text.SimpleDateFormat;
import java.util.Calendar;

public class MainActivity extends AppCompatActivity {
    private static StringBuilder log = new StringBuilder();
    private TextView textView;
    private VideoCastManager mManager;
    private Calendar cal = Calendar.getInstance();
    private SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        textView = (TextView) findViewById(R.id.log);
        Button button = (Button) findViewById(R.id.sendLog);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent send = new Intent(Intent.ACTION_SENDTO);
                String uriText = "mailto:" + Uri.encode("myemail") +
                        "?subject=" + Uri.encode("Logs") +
                        "&body=" + Uri.encode(log.toString());
                Uri uri = Uri.parse(uriText);

                send.setData(uri);
                startActivity(Intent.createChooser(send, "Send logs..."));
            }
        });
        mManager = VideoCastManager.initialize(getApplicationContext(), CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID, null, null);
        mManager.addVideoCastConsumer(new VideoCastConsumerImpl() {
            @Override
            public void onCastDeviceDetected(MediaRouter.RouteInfo info) {

                log("onCastDeviceDetected");
                log(info.toString());

            }

            @Override
            public void onCastAvailabilityChanged(boolean castPresent) {

                log("onCastAvailabilityChanged " + castPresent);


            }
        });
        mManager.startCastDiscovery();


        log("Is any route available now? " + isAnyRouteAvailable());


        new Handler(Looper.myLooper()).postDelayed(new Runnable() {
            @Override
            public void run() {


                log("Is any route available now (10 secs)? " + isAnyRouteAvailable());
            }
        }, 10000);
    }

    boolean isAnyRouteAvailable() {
        MediaRouter router = MediaRouter.getInstance(getApplicationContext());
        return router.isRouteAvailable(mManager.getMediaRouteSelector(),
                MediaRouter.AVAILABILITY_FLAG_IGNORE_DEFAULT_ROUTE
                        | MediaRouter.AVAILABILITY_FLAG_REQUIRE_MATCH);
    }

    private void log(String msg) {
        msg = "\n" + sdf.format(cal.getTime()) + " " + msg + "\n";

        log.append(msg);
        textView.setText(textView.getText() + msg);
    }


}
```

**Comment by naddaf** [comment]
out of curiosity, why the timestamp for those two logs are the same? I expected 10 seconds difference between the two?

**Comment by mntgoat** [comment]
Because I'm dumb :) I made my calendar instance outside the log method.

**Comment by naddaf** [comment]
I suggest you turn on verbose logging for the sdk and create a cpomplete log and send it over; that log has some information about discovery and we can look at that to see what is going on. To enable that, use `mCastManager.enableFeatures(VideoCastManager.FEATURE_DEBUGGING);`

**Comment by mntgoat** [comment]
Is there some easy way for the users to collect logs? I'll check if any of them know how to do it but it would be helpful.

**Comment by naddaf** [comment]
using "adb" is the easiest if they have the tools on their machine; short
of that, it gets complicated.

**Comment by naddaf** [comment]
Any update?

**Comment by mntgoat** [comment]
None of the users wanted to go through the process of capturing logs except for one who has a rooted phone. For some reason for him all the log capture apps I've had him tried only capture a few lines of logs even though his phone is rooted, so because of that I'm still working with him hoping to capture the right stuff at some point. I'll update this issue once I have something from him. Thanks for checking.

**Comment by naddaf** [comment]
Closing the issue for now; if you could provide the additional information, please let me know.

**Comment by deepmehtait** [comment]
@naddaf : I am having issue in discovery. I am able to get `onCastAvailabilityChanged` to true in case of devices in the network but I am not getting `onCastDeviceDetected` called. Only time it gets called is when I turn off and then turn on the wifi. Killing the app also wont work.

**Comment by entertailion** [comment]
CCL is not recommended for new development because it is only for Cast SDK v2. We recommend you migrate to Cast SDK v3 (Cast Application Framework): https://developers.google.com/cast/v2/android_migrate_sender
