### ISSUE TITLE
No call to onRemoteMediaPlayerStatusUpdated when playback ends

### ISSUE THREAD

**Issue by Appostrophe** [googlecast/CastCompanionLibrary-android#240]
Hi,

I do not receive any callback to onRemoteMediaPlayerStatusUpdated. But I can see that the Player activity is closed and the status of the chromecast connexion shifts to "no media selected".

How can I help you debug this issue?

Thank you

**Comment by naddaf** [comment]
Are you certain you have registered a VideoCastConsumer?

**Comment by Appostrophe** [comment]
Yes, I get all the other status update.

**Comment by Appostrophe** [comment]
As a matter of fact, when I remain idle for a couple of minutes after the end of the content, I receive the disconnection status update.

**Comment by Appostrophe** [comment]
I have hooked myself on the onApplicationStatusChanged callback. It is called when the content ends. 
Thank you!
