### ISSUE TITLE
Feature request : Add support for Audio Metadata

### ISSUE THREAD

**Issue by charly1811** [googlecast/CastCompanionLibrary-android#242]
```VideoCastManager``` can be used for Video casting but also audio casting. 
Even though it is possible to specify the content type when passing a media to ```VideoCastManager```, some metadata could not be displayed on the Cast device because of the Media Type sent to the Cast device. 

For example let's consider the following media:
TiTLE=MY AUDIO
URL=http://my/audio/url.mp3
ARTIST=ME
ALBUM=MY SONGS

even tough the media will be played as a song (because of content type ```audio/mp3```) the metadata ARTIST and ALBUM will not be displayed on the Cast device, because the url was sent to the cast device with the MediaType MediaMetadata.MEDIA_TYPE_MOVIE

That's why It could be a good idea to extend the ```Utils.bundleToMediaInfo()``` method:

* The Bundle passed to it could contain a value with the following key ```VideoCastManager.EXTRA_MEDIA_TYPE``` and the method will use it as media type. If the Bundle does not contains this key it will use the default value (```MediaMetadata.MEDIA_TYPE_MOVIE```) instead

* ```Utils.bundleToMediaInfo()``` could also extract audio specific metadata from the bundle if the media type is ```MediaMetadata.MEDIA_TYPE_MUSIC_TRACK```

**Comment by naddaf** [comment]
I will look into doing this in the next release.

**Comment by charly1811** [comment]
Thank you

**Comment by naddaf** [comment]
Added the following in v2.6:
- MediaType
- Album Title
- Album Artist
- Composer
- Release Date
