### ISSUE TITLE
Unsupported items in playlist causes Disconnect and Chromecast stops playing

### ISSUE THREAD

**Issue by softvision-mariusduna** [googlecast/CastCompanionLibrary-android#244]
Platform: IOS/Android
Hardware: Chromecast 1 and 2
Steps: Create a list of songs, make sure to have unsupported songs on playlist. Cast that array of songs to a Chromecast device.
Expected results: Whenever an unsupported media item is reached it will be skipped
Actual results: Chromecast disconnects and sops to play

**Comment by naddaf** [comment]
First, this is a receiver issue not a sender issue. Secondly, why do you expect  "Whenever an unsupported media item is reached it will be skipped"? If you have that expectation, you would then need to write your own receiver to handle that.

**Comment by softvision-mariusduna** [comment]
A new technical issue was logger to Chromecast Forum
https://productforums.google.com/forum/#!topic/chromecast/EcFGKlemZ44;context-place=topicsearchin/chromecast/Unsupported$20items
