### ISSUE TITLE
Utils.mediaInfoToBundle and Utils.bundleToMediaInfo don't get all params

### ISSUE THREAD

**Issue by aitorgomez** [googlecast/CastCompanionLibrary-android#245]
Hi.

I've been checking that Utils.mediaInfoToBundle() and Utils.bundleToMediaInfo() functions miss these parameters:

MediaMetadata.KEY_SERIES_TITLE
MediaMetadata.KEY_SEASON_NUMBER
MediaMetadata.KEY_EPISODE_NUMBER

So, the show name, season and episode number are never being displayed in the receiver app.

If I do the trick and do a quick edit on Utils.bundleToMediaInfo() function (just to ensure my receiver actually receives the missing params), it works fine.

Thank you

Aitor

**Comment by naddaf** [comment]
Addressed in 2.6.1
