### ISSUE TITLE
Metadata of RemoteMediaPlayer's MediaInfo is null

### ISSUE THREAD

**Issue by velvetk** [googlecast/CastCompanionLibrary-android#247]
I am trying to integrate CCL v-2.6 with my existing app and following closely the LocalPlayerActivity.java in CastVideos-android sample. The only difference is my video screen is a fragment instead of an activity. The MediaInfo and its metadata is setup before passing to CastManager's startVideoCastControllerActivity. Somehow the metadata of RemoteMediaPlayer's mediainfo is null. I registered both my phone and Chromecast with Cast SDK Developer Console. Here is the error log I am getting. Any help would be appreciated. Thanks for your time.

11-19 11:40:28.609 25258-25258/com.sample.app D/ccl_BaseCastManager: [v2.6] launchApp() is called
11-19 11:40:28.609 25258-25258/com.sample.app D/ccl_BaseCastManager: [v2.6] Launching app
11-19 11:40:28.688 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] onVolumeChanged() reached
11-19 11:40:28.689 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] onApplicationStatusChanged() reached: 
11-19 11:40:28.882 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] onApplicationStatusChanged() reached: null
11-19 11:40:29.386 25258-25258/com.sample.app D/ccl_BaseCastManager: [v2.6] launchApplication() -> success result
11-19 11:40:29.386 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] onApplicationConnected() reached with sessionId: 0FDFAB24-764D-4605-A80F-DA3D1D3BAFD4, and mReconnectionStatus=4
11-19 11:40:29.393 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] startNotificationService()
11-19 11:40:29.401 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] attachMediaChannel()
11-19 11:40:29.416 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] Registering MediaChannel namespace
11-19 11:40:29.419 25258-25258/com.sample.app D/MediaFragment: onApplicationLaunched() is reached
11-19 11:40:29.430 25258-25258/com.sample.app D/MediaFragment: onApplicationLaunched() is reached
11-19 11:40:29.456 25258-25258/com.sample.app D/ccl_BaseCastManager: [v2.6] Successfully added the new BaseCastConsumer listener com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService$1@950f311
11-19 11:40:29.456 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] Successfully added the new CastConsumer listener com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService$1@950f311
11-19 11:40:29.456 25258-25258/com.sample.app D/ccl_VideoCastNotificat: [v2.6] onStartCommand
11-19 11:40:29.456 25258-25258/com.sample.app D/ccl_VideoCastNotificat: [v2.6] onStartCommand(): Action: ACTION_VISIBILITY false
11-19 11:40:29.456 25258-25258/com.sample.app D/ccl_VideoCastNotificat: [v2.6] onRemoteMediaPlayerStatusUpdated() reached with status: 1
11-19 11:40:29.466 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] RemoteMediaPlayer::onStatusUpdated() is reached
11-19 11:40:29.466 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] onRemoteMediaPlayerStatusUpdated() reached
11-19 11:40:29.466 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] onQueueUpdated() reached
11-19 11:40:29.466 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] Queue Items size: 0, Item: null, Repeat Mode: 0, Shuffle: false
11-19 11:40:29.467 25258-25258/com.sample.app D/ccl_VideoCastManager: [v2.6] onRemoteMediaPlayerStatusUpdated(): Player status = playing
11-19 11:40:29.563 25258-25258/com.sample.app D/AndroidRuntime: Shutting down VM

11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime: Process: com.sample.app, PID: 25258
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.google.android.gms.cast.MediaMetadata.getImages()' on a null object reference
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.setBitmapForLockScreen(VideoCastManager.java:2267)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateLockScreenImage(VideoCastManager.java:2253)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.setUpMediaSession(VideoCastManager.java:2238)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSession(VideoCastManager.java:2329)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:2054)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$200(VideoCastManager.java:136)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$22.onStatusUpdated(VideoCastManager.java:1791)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated(Unknown Source)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.internal.zzm.zzbK(Unknown Source)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-19 11:40:29.700 25258-25258/com.sample.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by naddaf** [comment]
Please upgrade to 2.6.1 and try to reproduce it so I can see the right line numbers in the stack.

**Comment by velvetk** [comment]
Naddaf, thanks for your response. Here is the new error log after I upgraded to 2.6.1.

11-19 14:07:59.067 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] onVolumeChanged() reached
11-19 14:07:59.068 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] onApplicationStatusChanged() reached: 
11-19 14:07:59.068 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] joinApplication() -> failure
11-19 14:07:59.068 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] clearPersistedConnectionInfo(): Clearing persisted data for 12
11-19 14:07:59.068 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] cancelling reconnection task
11-19 14:07:59.069 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] onApplicationConnectionFailed() reached with errorCode: 2005
11-19 14:07:59.069 22419-22459/com.sample.app D/ccl_BaseCastManager: [v2.6.1] Reconnection: Attempt 3
11-19 14:07:59.069 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] disconnectDevice(true,false)
11-19 14:07:59.069 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] disconnectDevice() Disconnect Reason: App was taken over or not available anymore
11-19 14:07:59.069 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] mConnectionSuspended: false
11-19 14:07:59.069 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] clearPersistedConnectionInfo(): Clearing persisted data for 0
11-19 14:07:59.070 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] stopReconnectionService()
11-19 14:07:59.077 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] trying to detach media channel
11-19 14:07:59.077 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] Trying to disconnect
11-19 14:07:59.077 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] onDisconnected() reached
11-19 14:07:59.078 22419-22419/com.sample.app D/MediaFragment: onDisconnected() is reached
11-19 14:07:59.078 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] updateMiniControllersVisibility() reached with visibility: false
11-19 14:07:59.078 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] clearMediaSession()
11-19 14:08:02.312 22419-22419/com.sample.app D/MediaPlayer: setSubtitleAnchor in MediaPlayer
11-19 14:08:02.585 22419-22617/com.sample.app W/MediaPlayer: info/warning (3, 0)
11-19 14:08:04.498 22419-22419/com.sample.app W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
11-19 14:08:04.500 22419-22419/com.sample.app D/ccl_CastMediaRouterCal: [v2.6.1] onRouteSelected: info=MediaRouter.RouteInfo{ uniqueId=com.google.android.gms/.cast.media.CastMediaRouteProviderService:48dcf22888eed22664207d36268632c0, name=Rumble, description=Chromecast, iconUri=null, enabled=true, connecting=false, connectionState=0, canDisconnect=false, playbackType=1, playbackStream=-1, deviceType=0, volumeHandling=0, volume=0, volumeMax=20, presentationDisplayId=-1, extras=Bundle[{com.google.android.gms.cast.EXTRA_CAST_DEVICE="Rumble" (48dcf22888eed22664207d36268632c0)}], settingsIntent=null, providerPackageName=com.google.android.gms }
11-19 14:08:04.500 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] acquiring a connection to Google Play services for "Rumble" (48dcf22888eed22664207d36268632c0)
11-19 14:08:04.501 22419-22419/com.sample.app D/ccl_CastMediaRouterCal: [v2.6.1] onRouteSelected: mSelectedDevice=Rumble
11-19 14:08:05.047 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] onConnected() reached with prior suspension: false
11-19 14:08:05.050 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] launchApp() is called
11-19 14:08:05.050 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] Launching app
11-19 14:08:05.294 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] onVolumeChanged() reached
11-19 14:08:05.294 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] onApplicationStatusChanged() reached: 
11-19 14:08:05.486 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] onApplicationStatusChanged() reached: null
11-19 14:08:06.031 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] launchApplication() -> success result
11-19 14:08:06.032 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] onApplicationConnected() reached with sessionId: 3B0C1373-4DC3-4612-A2DD-7BCA42FC0779, and mReconnectionStatus=4
11-19 14:08:06.032 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] startNotificationService()
11-19 14:08:06.036 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] attachMediaChannel()
11-19 14:08:06.039 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] Registering MediaChannel namespace
11-19 14:08:06.044 22419-22419/com.sample.app D/MediaFragment: onApplicationLaunched() is reached
11-19 14:08:06.047 22419-22419/com.sample.app D/ccl_BaseCastManager: [v2.6.1] Successfully added the new BaseCastConsumer listener com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService$1@416ac08
11-19 14:08:06.047 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] Successfully added the new CastConsumer listener com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService$1@416ac08
11-19 14:08:06.048 22419-22419/com.sample.app D/ccl_VideoCastNotificat: [v2.6.1] onStartCommand
11-19 14:08:06.048 22419-22419/com.sample.app D/ccl_VideoCastNotificat: [v2.6.1] onStartCommand(): Action: ACTION_VISIBILITY false
11-19 14:08:06.048 22419-22419/com.sample.app D/ccl_VideoCastNotificat: [v2.6.1] onRemoteMediaPlayerStatusUpdated() reached with status: 1
11-19 14:08:06.197 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] RemoteMediaPlayer::onStatusUpdated() is reached
11-19 14:08:06.197 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] onRemoteMediaPlayerStatusUpdated() reached
11-19 14:08:06.197 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] onQueueUpdated() reached
11-19 14:08:06.198 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] Queue Items size: 0, Item: null, Repeat Mode: 0, Shuffle: false
11-19 14:08:06.198 22419-22419/com.sample.app D/ccl_VideoCastManager: [v2.6.1] onRemoteMediaPlayerStatusUpdated(): Player status = playing
11-19 14:08:06.232 22419-22419/com.sample.app D/AndroidRuntime: Shutting down VM
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime: FATAL EXCEPTION: main
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime: Process: com.sample.app, PID: 22419
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.cast.MediaMetadata.getString(java.lang.String)' on a null object reference
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.utils.Utils.mediaInfoToBundle(Utils.java:175)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.getCastControllerPendingIntent(VideoCastManager.java:2259)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.setUpMediaSession(VideoCastManager.java:2237)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSession(VideoCastManager.java:2354)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:2058)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$200(VideoCastManager.java:140)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$22.onStatusUpdated(VideoCastManager.java:1795)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated(Unknown Source)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.internal.zzm.zzbZ(Unknown Source)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-19 14:08:06.394 22419-22419/com.sample.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by naddaf** [comment]
It is strange that you are getting such NPE. I need to see your code/project; is that something you can share?

**Comment by velvetk** [comment]
Here is the video player fragment class. I have VideoCastManager initiated in Application subclass.

public class VideoPlayerFragment extends Fragment implements
        SurfaceHolder.Callback, OnPreparedListener, RumbleMediaController.MediaPlayerControl {

    SurfaceView videoSurface;
    MediaPlayer player;
    RumbleMediaController controller;
    private Media mMedia;
    private View fragmentView;
    private ProgressBar videoProgress;
    private int stopPosition;
    private Activity mActivity;
    private Menu mMenu;

    /* Indicates whether we are doing a local or a remote playback */
    public enum PlaybackLocation {
        LOCAL,
        REMOTE
    }
    /* List of various states that we can be in */
    public enum PlaybackState {
        PLAYING, PAUSED, BUFFERING, IDLE
    }
    private VideoCastManager mCastManager;
    private VideoCastConsumerImpl mCastConsumer;
    PlaybackState mPlaybackState;
    private static final String TAG = "MediaFragment";
    private MediaInfo mSelectedMedia;
    private PlaybackLocation mLocation;
    protected MediaInfo mRemoteMediaInformation;
    private Timer mControllersTimer;
    private final Handler mHandler = new Handler();


    static MediaFragment newInstance(Media mMedia) {
        MediaFragment mf = new MediaFragment();

        Bundle args = new Bundle();
        args.putParcelable("SELECTED_MEDIA", mMedia);
        mf.setArguments(args);

        return mf;
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        mActivity = (Activity)context;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mMedia = getArguments().getParcelable("SELECTED_MEDIA");

        mCastManager = VideoCastManager.getInstance();
        setupCastListener();
        mSelectedMedia = makeMediaInfo(mMedia.getTitle(), "Rumble Video", mMedia.getDescription(),
                (int)mMedia.getVideoLength(),
                mMedia.getMediaURL(),
                "videos/mp4",
                mMedia.getThumbnailURL(),
                mMedia.getThumbnailURL());
        mPlaybackState = PlaybackState.PLAYING;
        startControllersTimer();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        fragmentView = inflater.inflate(R.layout.fragment_media_video, container, false);

        return fragmentView;
    }

    @Override
    public void onResume() {
        super.onResume();

        if(getUserVisibleHint() && player != null && stopPosition >0) {
            player.start();
        }
        else {
            initVideo();
        }

        mCastManager.addVideoCastConsumer(mCastConsumer);
        mCastManager.incrementUiCounter();
        if (mCastManager.isConnected()) {
            updatePlaybackLocation(PlaybackLocation.REMOTE);
        } else {
            updatePlaybackLocation(PlaybackLocation.LOCAL);
        }
    }

    @Override
    public void onPause() {
        super.onPause();

        if (mLocation == PlaybackLocation.LOCAL) {
            pauseVideo();
            mPlaybackState = PlaybackState.PAUSED;
        }
        mCastManager.removeVideoCastConsumer(mCastConsumer);
        mCastManager.decrementUiCounter();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        ActionBar actionBar = ((AppCompatActivity) mActivity).getSupportActionBar();
        if(actionBar != null) {
            actionBar.show();
            mActivity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
            (mActivity.findViewById(R.id.record_button)).setVisibility(View.VISIBLE);
        }

        if (null != mCastManager && getUserVisibleHint()) {
            mCastConsumer = null;
        }
    }


    private void initVideo() {

        videoProgress = (ProgressBar) fragmentView.findViewById(R.id.videoProgress);
        videoProgress.setVisibility(View.VISIBLE);

        mVideoView.setOnPreparedListener(new OnPreparedListener() {
            @Override
            public void onPrepared(MediaPlayer mp) {
                videoProgress.setVisibility(View.GONE);
            }
        });

        mVideoView.setOnCompletionListener(new OnCompletionListener() {
            @Override
            public void onCompletion(MediaPlayer mp) {
                logView(mMedia.geteUrl());
            }
        });

        MediaController mediaController = new MediaController(mActivity);
        mVideoView.setMediaController(mediaController);

        mVideoView.setVideoURI(Uri.parse(mMedia.getMediaURL()));
        mVideoView.requestFocus();

        videoSurface = (SurfaceView) fragmentView.findViewById(R.id.videoSurface);
        videoSurface.getHolder().addCallback(this);
        player = new MediaPlayer();

        player.setScreenOnWhilePlaying(true);

        player.setOnCompletionListener(new OnCompletionListener() {
            @Override
            public void onCompletion(MediaPlayer mediaPlayer) {
                logView(mMedia.geteUrl());
            }
        });
        controller = new RumbleMediaController(mActivity);
        try {
            player.setAudioStreamType(AudioManager.STREAM_MUSIC);
            player.setDataSource(mActivity, Uri.parse(mMedia.getMediaURL()));
            player.setOnPreparedListener(this);
            if (stopPosition <= 0 && getUserVisibleHint()) {
                player.prepareAsync();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        FrameLayout videoFrame = (FrameLayout) fragmentView.findViewById(R.id.videoFrame);
        videoFrame.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                controller.toggleControlVisibility();
            }
        });
    }

    // Implement SurfaceHolder.Callback
    @Override
    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {

    }

    @Override
    public void surfaceCreated(SurfaceHolder holder) {
        if(player != null) {
            player.setDisplay(holder);
        }
    }

    @Override
    public void surfaceDestroyed(SurfaceHolder holder) {

    }

    // Implement MediaPlayer.OnPreparedListener
    @Override
    public void onPrepared(MediaPlayer mp) {
        videoProgress.setVisibility(View.GONE);
        controller.setMediaPlayer(this);
        controller.setAnchorView((FrameLayout) fragmentView.findViewById(R.id.videoFrame));

        if(player != null) {
            player.start();
            logView(mMedia.getvUrl());
        }
    }

    // Implement RumbleMediaController.MediaPlayerControl
    @Override
    public boolean canPause() {
        return true;
    }

    @Override
    public boolean canSeekBackward() {
        return true;
    }

    @Override
    public boolean canSeekForward() {
        return true;
    }

    @Override
    public int getBufferPercentage() {
        return 0;
    }

    @Override
    public int getCurrentPosition() {
        int currentPosition = 0;
        try {
            currentPosition = player.getCurrentPosition();
        }
        catch (Exception e) {
            e.printStackTrace();
        }

        return currentPosition;
    }

    @Override
    public int getDuration() {
        int duration = 0;
        try {
            duration = player.getDuration();
        }
        catch (Exception e) {
            e.printStackTrace();
        }

        return duration;
    }

    @Override
    public boolean isPlaying() {
        boolean isPlaying = false;
        try {
            isPlaying = player.isPlaying();
        }
        catch (Exception e) {
            e.printStackTrace();
        }

        return isPlaying;
    }

    @Override
    public void pause() {
        try {
            player.pause();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void seekTo(int i) {
        try {
            player.seekTo(i);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void start() {
        try {
            player.start();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }


    public void pauseVideo() {
        if (player != null) {
            player.pause();
            stopPosition = player.getCurrentPosition();
        }
    }


    @Override
    public void setMenuVisibility(final boolean visible) {
        super.setMenuVisibility(visible);

        if (visible && player != null) {
            if (stopPosition <= 0) {
                try {
                    videoProgress.setVisibility(View.VISIBLE);
                    player.setDataSource(mActivity, Uri.parse(mMedia.getMediaURL()));
                    player.prepareAsync();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            else {
                videoProgress.setVisibility(View.GONE);
                player.start();
            }
        }
    }

    @Override
    public void onStop() {
        super.onStop();
        if (player != null) {
            player.setScreenOnWhilePlaying(false);
            player.release();
            player = null;
        }
    }

    @SuppressLint("NewApi")
    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater menuInflater) {
        mMenu = menu;

        mCastManager.addMediaRouterButton(menu, R.id.media_route_menu_item);
    }

    private void setupCastListener() {
        mCastConsumer = new VideoCastConsumerImpl() {
            @Override
            public void onApplicationConnected(ApplicationMetadata appMetadata,
                                               String sessionId, boolean wasLaunched) {
                Log.d(TAG, "onApplicationLaunched() is reached");
                if (null != mSelectedMedia) {

                    if (mPlaybackState == PlaybackState.PLAYING) {
                        pauseVideo();
                        try {
                            loadRemoteMedia(player.getCurrentPosition(), true);
                            getActivity().finish();
                        } catch (Exception e) {
                            Utils.handleException(getActivity(), e);
                        }
                        return;
                    } else {
                        mPlaybackState = PlaybackState.IDLE;
                        updatePlaybackLocation(PlaybackLocation.REMOTE);
                    }
                }
                getActivity().invalidateOptionsMenu();
            }

            @Override
            public void onApplicationDisconnected(int errorCode) {
                Log.d(TAG, "onApplicationDisconnected() is reached with errorCode: " + errorCode);
                updatePlaybackLocation(PlaybackLocation.LOCAL);
            }

            @Override
            public void onDisconnected() {
                Log.d(TAG, "onDisconnected() is reached");
                mPlaybackState = PlaybackState.IDLE;
                mLocation = PlaybackLocation.LOCAL;
                getActivity().invalidateOptionsMenu();
            }

            @Override
            public void onRemoteMediaPlayerMetadataUpdated() {
                try {
                    mRemoteMediaInformation = mCastManager.getRemoteMediaInformation();
                } catch (Exception e) {
                    // silent
                }
            }

            @Override
            public void onFailed(int resourceId, int statusCode) {

            }

            @Override
            public void onConnectionSuspended(int cause) {
                Utils.showToast(getActivity(), R.string.connection_temp_lost);
            }

            @Override
            public void onConnectivityRecovered() {
                Utils.showToast(getActivity(), R.string.connection_recovered);
            }

        };
    }

    private void loadRemoteMedia(int position, boolean autoPlay) {
        if(getUserVisibleHint()) {
            mCastManager.startVideoCastControllerActivity(mActivity, mSelectedMedia, position, autoPlay);
        }
    }

    private MediaInfo makeMediaInfo(String title, String studio, String subTitle,
                                    int duration, String url, String mimeType, String imgUrl, String bigImageUrl) {

        MediaMetadata movieMetadata = new MediaMetadata(MediaMetadata.MEDIA_TYPE_MOVIE);

        movieMetadata.putString(MediaMetadata.KEY_SUBTITLE, studio);
        movieMetadata.putString(MediaMetadata.KEY_TITLE, title);
        movieMetadata.addImage(new WebImage(Uri.parse(imgUrl)));
        movieMetadata.addImage(new WebImage(Uri.parse(bigImageUrl)));
        JSONObject jsonObj = null;
        try {
            jsonObj = new JSONObject();
            jsonObj.put("description", subTitle);
        } catch (JSONException e) {
            Log.e(TAG, "Failed to add description to the json object", e);
        }

        return new MediaInfo.Builder(url)
                .setStreamType(MediaInfo.STREAM_TYPE_BUFFERED)
                .setContentType(mimeType)
                .setMetadata(movieMetadata)
                .setStreamDuration(duration * 1000)
                .setCustomData(jsonObj)
                .build();
    }

	private void updatePlaybackLocation(PlaybackLocation location) {
        mLocation = location;
        if (location == PlaybackLocation.LOCAL) {
            if (mPlaybackState == PlaybackState.PLAYING ||
                    mPlaybackState == PlaybackState.BUFFERING) {
                startControllersTimer();
            } else {
                stopControllersTimer();
            }

        } else {
            stopControllersTimer();
            updateControllersVisibility(false);
        }
    }

    private void startControllersTimer() {
        if (null != mControllersTimer) {
            mControllersTimer.cancel();
        }
        if (mLocation == PlaybackLocation.REMOTE) {
            return;
        }
        mControllersTimer = new Timer();
        mControllersTimer.schedule(new HideControllersTask(), 5000);
    }

    private class HideControllersTask extends TimerTask {

        @Override
        public void run() {
            mHandler.post(new Runnable() {
                @Override
                public void run() {
                    updateControllersVisibility(false);
                }
            });

        }
    }

    private void updateControllersVisibility(boolean show) {
        if (show) {
            controller.show();
        } else {
            controller.hide();
        }
    }

    private void stopControllersTimer() {
        if (null != mControllersTimer) {
            mControllersTimer.cancel();
        }
    }
}

**Comment by naddaf** [comment]
I need to be able to reproduce this; can you provide a minimal sample/test project that would exhibit the issue so you can share the project with me?

**Comment by velvetk** [comment]
It turns out that I picked the wrong app type when registering. Sorry for the inconvenience.

**Comment by r8tin-admin** [comment]
@velvetk, which app type should be registered to avoid this issue?

**Comment by velvetk** [comment]
I should have picked Styled Media Receiver instead of Remote Display Receiver.
