### ISSUE TITLE
Shuffle and Repeat

### ISSUE THREAD

**Issue by softvision-mariusduna** [googlecast/CastCompanionLibrary-android#248]
Shuffle and Repeat are not implemented for VideoCastControllerFragment. When will be implemented?

**Comment by naddaf** [comment]
For video content, it is not common to have those, is it?

**Comment by softvision-mariusduna** [comment]
For Chromecast we have Queue, there could be any media items, when playing shuffle and repeat may be usefull

**Comment by naddaf** [comment]
Currently there is no plan to add those to that activity.
