### ISSUE TITLE
Feature Request: Ability to customize notification

### ISSUE THREAD

**Issue by TR4Android** [googlecast/CastCompanionLibrary-android#250]
First off all, I really love your library. It makes cast integration way easier.
On thing I'd like to be able to do though is customization of the notification. I'd like to be able to change the layout of it, but I'm sure others would love to do other things, like changing the ticker icon or providing an additional related action.
One possible way of allowing this would be to add a method to the `VideoCastManager` that allows this (something like `setMediaNotificationBuilder(MediaNotificationBuilderCallback callback)` that has a method called `buildMediaNotification(...)` which has to be overidden). That would allow the default implementation to be applied if nothing has been set here, otherwise it will pass the call to this callback. The params of the `buildMediaNotification(...)` could be `MediaInfo info, Bitmap bitmap, boolean isPlaying, PendingIntent playbackIntent, PendingIntent stopIntent, PendingIntent contentIntent, String content, String token`.

What do you think? Would you welcome such a change?

**Comment by naddaf** [comment]
I am doing some work in that area to make it more customizable. Note that the notification in CCL now fully depends on NotificationCompat.MediaStyle so my customizations will be bound by that; i.e. I am not going to create a custom notification but within that restriction, there is room for making more actions available to the user. expect the next release to have more options there.

**Comment by TR4Android** [comment]
@naddaf That's good to hear. Thanks again for all the work you put into this library!

**Comment by TR4Android** [comment]
Sorry. Accidentally hit the close button here.

**Comment by naddaf** [comment]
v2.7.0 adds a number of different ways to customize notification. For one, there are now 5 pre-configured actions that developers can add out of the box: Play/Pause, Stop Cast, Skip Next, Skip Prev, Fast Forward and Rewind. If a developer wants something beyond those, then
1. Tthe VideoCastNotificationService needs to be subclassed and the "build()" method there needs to be overriden
2. The new implementation of notification needs to be declared in CastConfiguration.

**Comment by TR4Android** [comment]
@naddaf Awesome. Thanks for everything!  :smiley:
