### ISSUE TITLE
VideoCastControllerFragment does not re enter Immersive Mode

### ISSUE THREAD

**Issue by s3xy4ngyc** [googlecast/CastCompanionLibrary-android#251]
# Description:

When Clicking on The Cast Button inside the Cast Detail Screen (VideoCastControllerActivity/VideoCastControllerFragment), the Dialog Appearing Exits the Immersive Mode. when dismissing this dialog, the Screen does not Reenter into Immersive Mode.

# Steps to reproduce:
1. Used app is CastVideos (https://github.com/googlecast/CastVideos-android)
2. Play any Video Local
3. Connect to Chromecast
4. In the ChromecastControlls Screen click on Cast Button inside the Action bar
5. Dismiss the Dialog
6. Observe Immersive behavior.

# Technical Analysis

Currently Immersive mode gets set only inside VideoCastControllerFragment during onActivityCreated. However it never gets called again afterwards (e.g. onDismiss of dialoges)

**Comment by naddaf** [comment]
Changed that in v2.7.0 so it is called whenever the activity gains focus. It should mostly work; there might be some interactions there that can cause issue but for the most part, I *think* it is addressed.
