### ISSUE TITLE
Blue line appearing near toolbar when cast dialog is clicked on <= OS 4.4

### ISSUE THREAD

**Issue by christoff** [googlecast/CastCompanionLibrary-android#253]
Repro Steps:
1. Open CastVideos with a  <= OS 4.4 device
2. Play video
3. Click cast icon while videos is still playing

Expected Result:
A blue line should either be on top of the cast dialog or not exist at all.

Actual Result:
A blue line appears near the top of the app underneath the toolbar.

Screen:

![12-03-2015-12 30 06](https://cloud.githubusercontent.com/assets/20622/11574637/aead44b8-99c1-11e5-9d49-06eeded27449.png)

**Comment by naddaf** [comment]
CCL now has moved to use the defalt MediaRouteControllerDialog so this issue may not even be applicable any longer. Please test and report back if the issue still exists.

**Comment by christoff** [comment]
This is fixed with the default MediaRouteControllerDialog.

![12-11-2015-14 54 55](https://cloud.githubusercontent.com/assets/20622/11757586/67433f40-a017-11e5-9f8d-62d1979f63bb.png)
