### ISSUE TITLE
Alternative Setup Instructions

### ISSUE THREAD

**Issue by curlyfrie** [googlecast/CastCompanionLibrary-android#256]
Hi,
as mentioned in this post:
http://www.philosophicalhacker.com/2014/10/02/an-alternative-multiproject-setup-for-android-studio/

maybe a better way of including the CastCompanionLibrary (or at least a alternative) is to include it with these lines in the settings gradle:
```
include':CastCompanionLibrary'
project(':CastCompanionLibrary').projectDir = new File('../CastCompanionLibrary/')
```

otherwise it 'changed' my root directory (one level up) of the whole project in android studio; project view shows the folder one level up (dev workspace), and the android view shows an '..' module

**Comment by naddaf** [comment]
Ok, will do in the next update.

**Comment by naddaf** [comment]
Done in v2.7.1
