### ISSUE TITLE
Separate configuration for different casting types?

### ISSUE THREAD

**Issue by matiash** [googlecast/CastCompanionLibrary-android#257]
I'm writing an app that plays back both Video and Audio. The audio part is heavily inspired by the UniversalMusicPlayer sample (https://github.com/googlesamples/android-UniversalMusicPlayer) which uses CCL. For the video part I intended to base the code on CastVideos.

The problem I'm having is that while the VideoCastManager is a singleton, the configuration needed for the VideoCastManager for these two kind of playbacks is really quite different... 

For example, the audio playback uses its own notification manager. The CCL flow doesn't apply for this case -- the media notification should be visible *even when the playback is local on the device*, since playback is not tied to Activity lifecycle, while for videos this doesn't make sense. Also, the LocalPlayerActivity is not the same for these two kinds of media -- videos need a MediaPlayer, audio does not since it uses a Service. Etc.

I'm a bit confused as to what would be good practice to handle cases like this.

**Comment by naddaf** [comment]
CCL is mostly focused around Video. For pure audio cases, you can follow what UniversalMusicPlayer has done. For a mix of Video and Audio, that is not a common use case; there aren't that many app out there that try to handle both in the same app so there hasn't been any effort in handling it in CCL.
