### ISSUE TITLE
Dialog for disconnect in landscape mode

### ISSUE THREAD

**Issue by PetrSklenicka** [googlecast/CastCompanionLibrary-android#258]
Hello,
when I tap to disconnect button in toolbar in VideoCastControllerActivity, the dialog for disconnect appears. If I have the device in landscape mode, the dialog is bigger than my screen and dialog has no ability to scroll down. See the attached image, please. 
Is there any way how can I solve this? 
![disconnect](https://cloud.githubusercontent.com/assets/5917696/11952862/0e1b1a72-a89c-11e5-9bb8-b29a81533db8.png)

**Comment by naddaf** [comment]
What version of mediarouter support library are you using? Can you reproduce that in CastVideos-android app (you need to remove the portrait restriction on, say, VideoBrowserActivity in the manifest). I am not able to reproduce that there' in landscape, it hides the image so everything fits in the screen.

**Comment by PetrSklenicka** [comment]
Thank you for your response and advice. You are right, I was using older version of mediarouter support lib - I was using 19.1.0. Now, I am using version 23.0.1 and everything looks fine. It was my mistake, so thank you again and you can close this issue.

**Comment by naddaf** [comment]
Please use 23.1.1, that is the latest and has addressed some issues in 23.0.1 as well. Glad to hear all is working now.
