### ISSUE TITLE
Styles of dialogs

### ISSUE THREAD

**Issue by PetrSklenicka** [googlecast/CastCompanionLibrary-android#259]
Hello,
I am using your library and I have an issue with styles of dialogs. See my attached screenshots, please. Screenshots are from device Nexus 5 with Android 6.0.1. You can see in the first picture, that dialog is too large and there is missing disconnect button in this dialog. In the second picture there is not visible icon for changing volume.
Is there any way how can I adjust the layouts of these two dialogs?

![cast2](https://cloud.githubusercontent.com/assets/5917696/11973874/3349df7c-a95f-11e5-9b31-5b6ced008cf7.png)

![casting](https://cloud.githubusercontent.com/assets/5917696/11973879/399fec90-a95f-11e5-9a07-1c2114b9c626.png)

**Comment by naddaf** [comment]
For the first issue, what version of mediarouter support lib are you using? For the second one, what is different that you have done compared to the first one? I cannot reproduce any of these; try to reproduce these in CastVideos-anadoid sample.

**Comment by PetrSklenicka** [comment]
Thank you for your response and advice. You are right, I was using older version of mediarouter support lib - I was using 19.1.0. Now, I am using version 23.0.1 and everything looks fine. It was my mistake, so thank you again and you can close this issue.

**Comment by naddaf** [comment]
Please switch to 23.1.1 to have the latest and greatest.
