### ISSUE TITLE
Remote AAR hosting (bintray, maven central, jcenter)

### ISSUE THREAD

**Issue by jpshelley** [googlecast/CastCompanionLibrary-android#260]
I've seen numerous tickets asking for public hosting, dating years back now.

Will this ever be an official google library that gets hosted for easy consumption? I know the policies at google make it complicated like you said, but is there a reason for not hosting it yet?

Thanks

**Comment by naddaf** [comment]
I have started working on that already and I am hoping by the end of this month (or around that time frame) I have the library available through jcenter and maven central. I will let the community know when that happens. I'll keep this ticket open to track the progress on that as well.

**Comment by jpshelley** [comment]
:100: Awesome to hear!

**Comment by naddaf** [comment]
Just an update on this: work is coming along well and I am hoping soon I can have that ready; it might be just through jCenter.

**Comment by naddaf** [comment]
It is now live on jCenter, use the following to include the library:

compile 'com.google.android.libraries.cast.companionlibrary:ccl:2.7.4'

Make sure jCenter is in your repositories. You would also need to explicitly include dependencies on Play Services and support libraries.

**Comment by jpshelley** [comment]
Thanks @naddaf! :+1:
