### ISSUE TITLE
VideoCastManager, onPlayPauseClicked, resume stream is not working for live streams 

### ISSUE THREAD

**Issue by curlyfrie** [googlecast/CastCompanionLibrary-android#261]
Hi,
I know you mentioned before that the receiver should handle what happens when live content is paused.

What I noticed, if content is live and gets paused, it cannot be resumed with the mini controller (works fine via media controller dialog) because the player state is also MediaStatus.PLAYER_STATE_PAUSED (not IDLE).

Therefore, maybe the onPlayPauseClicked in VideoCastManager should be updated, (maybe something similar to this:

```
@Override
public void onPlayPauseClicked(View v) throws CastException, TransientNetworkDisconnectionException, NoConnectionException {
	checkConnectivity();
	if (mState == MediaStatus.PLAYER_STATE_PLAYING) {
		pause();
	} else if (mState == MediaStatus.PLAYER_STATE_PAUSED || mState == MediaStatus.PLAYER_STATE_IDLE) {
			play();
	}
}
```

**Comment by naddaf** [comment]
I have already mentioned that for pausing a live stream, sender device needs to receive an idle (sine it is not really a pause).

**Comment by curlyfrie** [comment]
Ok I understand, thx for clearing this up.

In this case the receiver should send an IDLE state if live stream, although the sender sends an pause event? Then that problem lies whithin the cast.receiver.Mediamanager?

If I set the state to IDLE myself in *customizedStatusCallback_*
I of course get an *onRemoteMediaPlayerStatusUpdated(): Unexpected Idle Reason 0*

**Comment by naddaf** [comment]
Make sure the reason is also set to MediaStatus.IDLE_REASON_CANCELED, it seems, based on the message you mentioned, that you are not setting that (see section Live Streams in the CCL's pdf documentation)

**Comment by curlyfrie** [comment]
oh thx for the hint.. you're right that was the problem, i added the IDLE_REASON_CANCELED and it works.
so this is a possible solution till maybe the mediamanager is updated to send idle in the first playce for live streams.
