### ISSUE TITLE
There is crash log

### ISSUE THREAD

**Issue by akkie2010** [googlecast/CastCompanionLibrary-android#262]
01-14 04:46:49.229: E/AndroidRuntime(19361): FATAL EXCEPTION: main
01-14 04:46:49.229: E/AndroidRuntime(19361): java.lang.NullPointerException
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:689)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:666)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:633)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at com.google.android.libraries.cast.companionlibrary.utils.Utils.scaleAndCenterCropBitmap(Utils.java:373)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService$2.onPostExecute(VideoCastNotificationService.java:231)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService$2.onPostExecute(VideoCastNotificationService.java:227)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at android.os.AsyncTask.finish(AsyncTask.java:631)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at android.os.Looper.loop(Looper.java:152)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at android.app.ActivityThread.main(ActivityThread.java:5132)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at java.lang.reflect.Method.invoke(Method.java:511)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
01-14 04:46:49.229: E/AndroidRuntime(19361): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by naddaf** [comment]
I am not able to reproduce this, need reproduction steps. What version of CCL are you using? Also, can you reproduce this with CastVideos app?

**Comment by naddaf** [comment]
Closed due to lack of feedback. Please reopen if you have repro steps.
