### ISSUE TITLE
xiaomi phones mVideoManager.isAnyRouteAvailable() returns false always

### ISSUE THREAD

**Issue by PMNasrudeen** [googlecast/CastCompanionLibrary-android#263]
Hi,
I use following code to show toolbar only if chromecast device is available.

    mVideoManager = VideoCastManager.getInstance();
    mtoolbar.setVisibility(mVideoManager.isAnyRouteAvailable()
                    ? View.VISIBLE : View.GONE);

If chromecast device is available, `mVideoManager.isAnyRouteAvailable()` returns `true` in all mobile, except in xiaomi mobiles ,  xiaomi mobiles always return `false`, Any workaround for xiaomi?

**Comment by naddaf** [comment]
I am not familiar with Xiaomi devices and if they have done anything unconventional. I presume play services is available there?
