### ISSUE TITLE
Feature Request: ability to set the MediaRouteDialogFactory

### ISSUE THREAD

**Issue by kevinzetterstrom** [googlecast/CastCompanionLibrary-android#265]
It would be a great addition to have the ability to set a MediaRouteDialogFactory so that it could be returned in VideoCastManager ```getMediaRouteDialogFactory```. Currently, this method just returns null, and in order to not have null returned, we need to locally modify the VideoCastManager class.

This was my originally proposed [solution](https://github.com/googlecast/CastCompanionLibrary-android/pull/264)

**Comment by naddaf** [comment]
Version 2.7.3 which was just published has the change needed for this. You should use the CastConfiguration class to set your own factory. If not, it will use the default one. This has the advantage of:
1. Being treated like any other configuration setting
2. I didn't want to have that dialog re-defined dynamically; it should have been a one-time setting as part of the initialization. Using a setter would not allow for that.

**Comment by kevinzetterstrom** [comment]
Thanks!
