### ISSUE TITLE
Backgound image in VideoCastControllerActivity broken

### ISSUE THREAD

**Issue by jadlr** [googlecast/CastCompanionLibrary-android#269]
Screenshots explain this best: (device is a Nexus 5  / Android 6)

v2.7.1
![screenshot_20160129-155701](https://cloud.githubusercontent.com/assets/696999/12678917/8ce78174-c6a1-11e5-8ec0-52f8d4076dde.png)

v2.7.3
![screenshot_20160129-155352](https://cloud.githubusercontent.com/assets/696999/12678932/9edbd1be-c6a1-11e5-8c74-66fa395271a5.png)

**Comment by naddaf** [comment]
2.7.3 tried to be a bit more conservative about the image sizes to avoid running into OOM. Can you tell me:
1. what is the screen size/resolution of your device
2. what is the native resolution of the image?

**Comment by jadlr** [comment]
Resolution is: 1080 x 1920 pixels (~445 ppi pixel density)

Will find out about the image

**Comment by naddaf** [comment]
when I inspect the original image you have posted, I get 699x349, is that correct?

**Comment by naddaf** [comment]
Can you give me the url pointing to this image if possible? The same url that your app is using.

**Comment by naddaf** [comment]
never mind, I can reproduce this. I will address it.

**Comment by naddaf** [comment]
Should be fixed in v2.7.4, get the head of the tree for a fix.

**Comment by jadlr** [comment]
thank you very much! :+1:

**Comment by naddaf** [comment]
Could you please give it a try and let me know?

**Comment by jadlr** [comment]
I will give you feedback on Monday. Everything I need to test is at work...

Have a nice weekend!

**Comment by jadlr** [comment]
@naddaf It works as expected in version 2.7.4! Thanks for the quick response/fix
