### ISSUE TITLE
Wrong Button background color in IntroductoryOverlay on Android 4.x

### ISSUE THREAD

**Issue by rhlff** [googlecast/CastCompanionLibrary-android#272]
The background color of the Button in IntroductoryOverlay is always a light grey on Android 4.x. I tested it with a 4.4 device and the emulator. It works fine with Android 5+ (see the attached image).

I think maybe `mButton.getBackground().setColorFilter(buttonColor, PorterDuff.Mode.MULTIPLY);` in [IntroductoryOverlay](https://github.com/googlecast/CastCompanionLibrary-android/blob/master/src/com/google/android/libraries/cast/companionlibrary/widgets/IntroductoryOverlay.java#L185) causes this?

![Wrong Button color](http://i.imgur.com/PgOkgVr.png)

**Comment by naddaf** [comment]
Thanks for catching that. That line you have there is not the issue; it is rather related to styling buttons for pre-M versions; the correct fix is to use AppCompatButton to provide tinting for earlier versions and that is what I will do in the next update.

**Comment by naddaf** [comment]
If you want to have a fix before I publish the update, please try adding the following line to the <Button/> element in layout/ccl_intro_overlay.xml 

style="@style/Widget.AppCompat.Button.Colored"

and let me know if it addresses the issue.

**Comment by rhlff** [comment]
Yep, that addresses the issue. Thanks.

**Comment by naddaf** [comment]
Is fixed in v2.8.0
