### ISSUE TITLE
VideoCastManager doesn't clear mMediaStatus after disconnect

### ISSUE THREAD

**Issue by vandzi** [googlecast/CastCompanionLibrary-android#273]
Steps to reproduce
- connect to chromecast and play something
- disconnect
- connect again
- call VideoCastManager.getMediaStatus() in onApplicationConnected
VideoCastManager.getMediaStatus() has state "playing" instead of idle. 

expected - mediaStatus has state PLAYER_STATE_UNKNOWN/PLAYER_STATE_IDLE or is null.

**Comment by naddaf** [comment]
Should be fixed in v2.8.0
