### ISSUE TITLE
Trying to play a video with no active media session

### ISSUE THREAD

**Issue by malsabbagh** [googlecast/CastCompanionLibrary-android#274]
I tried the new 2.8 version but I am always getting (mRemoteMediaPlayer == null)
Same code with 2.7.4 doesn't have this issue. I went through the documentation but nothing new to VideoCastManager initialization. 
Can someone have a look?

Thanks,

**Comment by naddaf** [comment]
Is this happening with CastVideos-android app?

**Comment by malsabbagh** [comment]
CastVideos-android app works fine so I tested all the options for CastConfiguration in that sample with my application and once I add the following option it works fine:
"setLaunchOptions(false, Locale.getDefault())"

Is it now mandatory?

**Comment by malsabbagh** [comment]
Removing that option from the CastVideos-android app breaks it as well.

**Comment by naddaf** [comment]
It is a bug that was there in earlier versions but was not exposed; a change in 2.8.0 is now exposing that. For now, set the LaunchOptions till I fix that in the next update, thanks for reporting that.

**Comment by naddaf** [comment]
Addressed in v2.8.1
