### ISSUE TITLE
receiver app doesn't launch without launchOptions object

### ISSUE THREAD

**Issue by vandzi** [googlecast/CastCompanionLibrary-android#277]
receiver app doesn't launch if launchOptions is null.
Cast.CastApi.launchApplication(mApiClient, applicationId, launchOptions)

launchOptions is always null if you don't specify it for CastConfiguration because launchApp uses object from CastConfiguration
 launchApp(mCastConfiguration.getApplicationId(), mCastConfiguration.getLaunchOptions()); so mLaunchOptions is ignored

**Comment by naddaf** [comment]
This is a duplicate of $274
