### ISSUE TITLE
Sound level control doesn't display correct value

### ISSUE THREAD

**Issue by vandzi** [googlecast/CastCompanionLibrary-android#281]
Reproduced with CastVideos-android sample app.
Action Performed
1. Open the app
2. Start casting 
3. Go to cast menu
4. Swipe sound level multiple times

Expected Result
It should show actual sound level
Actual Result
It shows incorrect(previous) sound level

**Comment by naddaf** [comment]
Cast menu (i.e. MediaRouteChooserDialog) is created and handled by Media Router support library and not CCL, so if there is any issue related to the functionality of that dialog, you would need to open a bug against that support library, not CCL.

**Comment by vandzi** [comment]
Same applies to VideoMediaRouteControllerDialog

**Comment by naddaf** [comment]
No, sample app uses the one provided by the media route support library, see BaseCastManagergetMediaRouteDialogFactory().
