### ISSUE TITLE
IntroductoryOverlay shows under DialogFragment 

### ISSUE THREAD

**Issue by ad1Dima** [googlecast/CastCompanionLibrary-android#285]
Because of DialogFragment shows in separate Window and IntroductoryOverlay shows in Window hosting Activity, overlay appears under DialogFragment

**Comment by naddaf** [comment]
Which DialogFragment is this? Why is there a dialog at all?

**Comment by ad1Dima** [comment]
By design app on tablet has item profile in DialogFragment with MediaRouteButton inside.

**Comment by naddaf** [comment]
Not sure what you mean by "Item Profile"

**Comment by ad1Dima** [comment]
Unfortunately I cant show you screen. In my app I have collection of videos. On tablet each video has profile page that is DialogFragment. Inside this DialogFragment I have MediaRouteButton. I whant to use IntroductoryOverlay but it shows under DialogFragment.

**Comment by naddaf** [comment]
Then you'd need to handcraft your own solution; that is not a common enough scenario to be covered by the library.
