### ISSUE TITLE
Gradle cannot find google play-services-cast

### ISSUE THREAD

**Issue by chjan** [googlecast/CastCompanionLibrary-android#288]
To the below error, please note that an Ant based alternative project find the library file google-play-services.jar without problems. The Ant version compiles and finds all classes. But as it seems, Gradle cannot interpret correctly this statement in the file build.gradle, 

`dependencies` { compile `'com.google.android.gms:play-services-cast:8.4.0'`

This is causing a flow of class not found errors. Despite this, the project will build successfully. 

Therefore attempting Run (just as a provocation to find the error), the error report is listed below. Notice the strange jar filenames that Gradle searches for, for example ".../play-services-cast.jar".
Shouldn't Gradle be looking for google-play-services.jar?

I am new to Gradle and I am using Netbeans with Gradle plugin, a duo which is working fine otherwise.

* What went wrong:
A problem occurred configuring root project 'CastCompanionLibrary-android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.google.android.gms:play-services-cast:.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-cast//play-services-cast-.pom
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-cast//play-services-cast-.jar
         file:/C:/Users/CarlHenrik/Documents/NetBeansProjects/SDKs/CastCompanionLibrary-android/libs/play-services-cast-.jar
         file:/C:/Users/CarlHenrik/Documents/NetBeansProjects/SDKs/CastCompanionLibrary-android/libs/play-services-cast.jar

**Comment by naddaf** [comment]
Make sure your SDK is up to date, including google repositories and support libs repositories (all can be updated using the SDK manager).

**Comment by chjan** [comment]
The SDK is indeed updated to the latest versions. This is why I stated that an ANT alterative project configuration is succesful, using the exact same /libs folder of the Gradle project. Please do not close until problem solved. Thanks

**Comment by naddaf** [comment]
As I said earlier, your environment is not correctly set up; when gradle looks for the Play Services, it should find them inside your Android SDK folder for that. I don't know what Netbeans does and what the gradle plugin is for netbeans. As a test, you can checkout CCL into an empty directory, go into the CCL's root directory and type "./gradlew build" and see what you get.
