### ISSUE TITLE
A suggested bugfix for build.gradle

### ISSUE THREAD

**Issue by chjan** [googlecast/CastCompanionLibrary-android#289]
I had trouble with a definition in the build.gradle and here is how I fixed it. I am using Netbeans 8.1 with Gradle plugins for Java and Android. I have the latest of all libraries installed via Android SDK Manager

 // NOT WORKING: compile` 'com.google.android.gms:play-services-cast:8.4.0'
//USE THE FOLLOWING LINE, WORKING:
    compile files('libs/google-play-services.jar')

**Comment by naddaf** [comment]
No, that is not right; the current compile` 'com.google.android.gms:play-services-cast:8.4.0' is correct and your suggestion is indeed wrong; Play Services includes resources that are missing from jar packages. In addition, te project should use the Play Services that come with the official Android SDK and its extra/additional downloads and not on developer's lib folder.

**Comment by chjan** [comment]
naddaf, I am a newcomer using Windows, and I realize I could be misunderstanding things at the moment, but please help me with specific comments to pass the CastCompanion going.

1. You say "In addition, the project should use the Play Services that come with the official Android SDK and its extra/additional downloads and not on developer's lib folder."

But if you look to the https://developers.google.com/android/guides/setup#add_google_play_services_to_your_project, exactly the opposite is recommended under the tab OTHER, even in blue extra important remark, as follows: 

"Note: You should be referencing a copy of the library that you copied to your development workspace—you should not reference the library directly from the Android SDK directory."

What is it with CastCompanion that makes you state the opposite recommendation?

And when I precisely follow this tutorial linked above, I find the following file, which I then copy to my local library:C:\Program Files (x86)\Android\android-sdk\extras\google\google_play_services\libproject\google-play-services_lib\libs\google-play-services.jar

I am therefore following the tutorial with a teaspoon. Where do I do wrong here?

2. I importantly need to understand this: What is really the play-services-cast:8.4.0, as compared to the content in the file google-play-services.jar? Evidently the classes must necessarily be in a file. Can you please tell me the name of this file containing the "play-services-cast:8.4.0" so that I can search the Official Android SDK folder installed on my computer?

3. What is the version 8.4.0 and how do I ensure that I have the correct version downloaded?

**Comment by chjan** [comment]
I need to add one more comment after further trials and tribulations. I am able to fetch the latest versions using either MavenLocal() or MavenCentral() for these three libraries as specified in the build.gradle:
```
dependencies {
compile "com.android.support:appcompat-v7:${supportLibVersion}" 
compile "com.android.support:mediarouter-v7:${supportLibVersion}"
compile 'com.google.android.gms:play-services-cast:8.4.0'
}
```
This is not enough. I also need to add the following dependencies: 
```
dependencies {
compile files('libs/google-play-services.jar')
}
```
else the following class does not exist: com.google.android.gms.common.
```
dependencies {
compile files('libs/android-support-v4.jar')
}
```
else for example these two classes do not exist:
android.support.v4.media.MediaMetadataCompat;
android.support.v4.view.MenuItemCompat;

Thanks for any response as to why this happens.

**Comment by naddaf** [comment]
Play Services is downloaded by your Android SDK manager and put under your SDK folder; under that directory, you can find it at: extras/google/m2repository/com/google/android/gms/play-services/ and it has different folders for different versions, so you might want to check what versions are installed. Similar to Play Services base package, there is a folder play-services-cast too. Packages that are used by gradle are *.aar and not just *.jar; the AAR packages include resources. Regarding the local copy in your libs directory, the only supported IDE is Android Studio and gradle uses a local maven repo inside the SDK (at the location I gave above) to find play services, so you SHOULD NOT copy them into your local libs directory (i.e. the Other tab that you referenced above is not relevant to this discussion).

**Comment by chjan** [comment]
Yes, as I already stated I have found all the relevant folders containing google-play-services, play-services-cast, etc. Exactly as you point out. What I still do not understand is how gradle will fetch google-play-services even if this particular service is not defined in the module-level build.gradle, i.e. the build.gradle defined in CastCompanion subfolder? Because play-services-cast seems to be a small addendum to google-play-services only. 

This is why I was wondering if google-play-services is defined in your top-level build.gradle? If the answer is yes, then problem is solved. If the answer is no, then I must ask if the "search" for e.g. google-play-services is "hardcoded" into AndroidStudio? My guess is it is found in the top level build.gradle. Please elaborate on this. Thanks again. (The reason I ask is to understand for a next project).

**Comment by naddaf** [comment]
Gradle is smart enough to try to resolve dependencies. When you set in your build file that your project depends on play-services-cast, gradle tries to see if this has any dependencies and if it does, it looks for ways to bring in the dependencies; in this case, the cast extension to play services hasd dependency on the base and as a result, it searches for the base and if it finds, it brings that in. Here is when you look at the dependency hierarchy for CCL:

```
$ ./gradlew dependencies
:dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

_debugAndroidTestApk - ## Internal use, do not manually configure ##
+--- com.android.support:appcompat-v7:23.2.1
|    +--- com.android.support:support-v4:23.2.1
|    |    \--- com.android.support:support-annotations:23.2.1
|    +--- com.android.support:animated-vector-drawable:23.2.1
|    |    \--- com.android.support:support-vector-drawable:23.2.1
|    |         \--- com.android.support:support-v4:23.2.1 (*)
|    \--- com.android.support:support-vector-drawable:23.2.1 (*)
+--- com.android.support:mediarouter-v7:23.2.1
|    +--- com.android.support:appcompat-v7:23.2.1 (*)
|    \--- com.android.support:palette-v7:23.2.1
|         \--- com.android.support:support-v4:23.2.1 (*)
\--- com.google.android.gms:play-services-cast:8.4.0
     +--- com.google.android.gms:play-services-base:8.4.0
     |    \--- com.google.android.gms:play-services-basement:8.4.0
     |         \--- com.android.support:support-v4:23.0.0 -> 23.2.1 (*)
     \--- com.android.support:mediarouter-v7:23.0.0 -> 23.2.1 (*)
```

If you have more questions on how gradle works, you should ask those on gradle related forums; CCL works as it should in this respect.

**Comment by chjan** [comment]
Thanks. I am starting to grasp how this works. I would say that when this hidden "smartness" does not work, it becomes a timethief, because it is just that; hidden, thus unknown. 

Regarding "gradle is smart enough", this is as it seems true in your case with the supported Android Studio, however the gradle under Netbeans is not  as smart. And perhaps eclipse would be in trouble too. 

Generally, Iit can be a a good thing to define all dependencies in the build file. This is much more easy to understand and for this project it would have made this whole thread redundant. 

For your consideration, but thanks for taking the time to give me good responses.
