### ISSUE TITLE
How to set theme for MediaRouteControllerDialog?

### ISSUE THREAD

**Issue by dan-silver** [googlecast/CastCompanionLibrary-android#290]
Is it possible to set the dialog theme for MediaRouteControllerDialog?  I've searched the documentation, but can't seem to find anything. In my app, it for some reason doesn't default to the app theme and the audio icon isn't clearly visible.

Thanks and awesome library!
-Dan

![wrong-theme](https://cloud.githubusercontent.com/assets/1266893/14235874/70ab8cc0-f9bf-11e5-95df-9f3df191fdee.png)

**Comment by naddaf** [comment]
Take a look at [MediaRouterThemeHelper.java](https://android.googlesource.com/platform/frameworks/support/+/master/v7/mediarouter/src/android/support/v7/app/MediaRouterThemeHelper.java); that is mainly what is used in theming the dialog.

**Comment by dan-silver** [comment]
Great, thanks for the fast reply. I'll take a look at that helper class.

For anyone else running into this, it looks like this has already been reported as a bug at https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&groupby=&sort=&id=198714

They said it's been fixed internally, but haven't clarified if it's been released in a public update.

**Comment by naddaf** [comment]
Since this is not a CCL issue, I am closing this; if you believe it is indeed a CCL issue comment here and I will reopen.
