### ISSUE TITLE
Mediaroute menu item highlight in IntroductoryOverlay is not in correct place when multiple items are there in actionbar.

### ISSUE THREAD

**Issue by rini-m** [googlecast/CastCompanionLibrary-android#291]
In my app, there is a search button next to media route button. When ovelrlay is shown, highlight is somewhere on left top corner than on media route button. Could you please help me to fix this issue?

**Comment by naddaf** [comment]
I cannot reproduce this; I enabled the additional icon/action for queue in CastVideos-android to have additional item there and it correctly highlighted the MR button. Please try to reproduce the issue in CastVideos app and provide a sample that shows the issue.

**Comment by rini-m** [comment]
Hi, Thanks for the reply.  Issue occurred because mediaRouteMenuItem.isVisible() check was not done. After adding it, issue is no more reproducible.
