### ISSUE TITLE
No video after switching an audio track.

### ISSUE THREAD

**Issue by AtatakaiNeko** [googlecast/CastCompanionLibrary-android#297]
I'm using built-in dialog(the one that allows to switch audio and subtitles streams) to allow user to switch between different audio stream in my video streaming application. My MediaInfo object has 3 MediaTracks objects:
- Video
- Audio - ENG
- Audio - IT

After switching from ENG to IT audio stream a video on a receiver disappears. After some investigation I found this code in the library in TracksChooserDialog:
```
List<MediaTrack> selectedTracks = new ArrayList<>();
MediaTrack textTrack = mTextAdapter.getSelectedTrack();
if (textTrack.getId() != TEXT_TRACK_NONE_ID) {
    selectedTracks.add(textTrack);
}
MediaTrack audioVideoTrack = mAudioVideoAdapter.getSelectedTrack();
if (audioVideoTrack != null) {
    selectedTracks.add(audioVideoTrack);
}
mCastManager.notifyTracksSelectedListeners(selectedTracks);
```
mAudioVideoAdapter contains only audio tracks information. So it is kinda confusing. As you can see, after selecting new audio track, library forgets to include a video track in a list of active tracks, which leads to a black screen in a receiver application(though audio works as expected.)

I have a workaround in my app to make sure that a MediaTrack with type TYPE_VIDEO(if such exists) is always added as active.

**Comment by naddaf** [comment]
Do you see any Video Track when you query for the active tracks (before changing your audio track)?

**Comment by AtatakaiNeko** [comment]
Yes, I can see one active Video Track in the array of active tracks prior this line: `mCastManager.notifyTracksSelectedListeners(selectedTracks);`

**Comment by naddaf** [comment]
This is a bit of unsupported case due to the receiver SDK but I have made some code changes in v2.8.4, hopefully that will address your issue.
