### ISSUE TITLE
A KEY_TRACK_CONTENT_TYPE param is missing in Utils.mediaInfoToBundle()

### ISSUE THREAD

**Issue by aitorgomez** [googlecast/CastCompanionLibrary-android#298]
When using Utils.mediaInfoToBundle(), "trackContentType" value is not set into the bundle, even if set when using MediaTrack.Builder().setContentType() function.

Same when using bundleToMediaInfo() back.

**Comment by naddaf** [comment]
Addressed in v2.8.4
