### ISSUE TITLE
MiniController does not resume live streams

### ISSUE THREAD

**Issue by blunan** [googlecast/CastCompanionLibrary-android#299]
While casting a live stream content the mini controller let you pause it, but when you press the play button to resume it, no actual resume is done.

After some debugging I found that the mini controller calls the onPlayPauseClicked(View v) method in the VideoCastManger, this one has a bug where it does not call the play() method if is a paused live stream.

**Comment by naddaf** [comment]
The current implementation is:
```   java
    public void onPlayPauseClicked(View v) throws CastException,
            TransientNetworkDisconnectionException, NoConnectionException {
        checkConnectivity();
        if (mState == MediaStatus.PLAYER_STATE_PLAYING) {
            pause();
        } else {
            boolean isLive = isRemoteStreamLive();
            if ((mState == MediaStatus.PLAYER_STATE_PAUSED && !isLive)
                    || (mState == MediaStatus.PLAYER_STATE_IDLE && isLive)) {
                play();
            }
        }
    }
```

and it does take care of the live stream. Based on the CCL's convention, when you have a live stream and you pause the stream, your receiver should send a media status update of IDLE with reason=canceled (see CCL's documentation). The reason for that convention is that a "pause" is not really a pause, you don't have a DVR functionality so pause is really "stop the stream but don't unload it" and when user clicks on play, it should just start the stream from the current time. As a result, using the PAUSE state was not appropriate and CCL's chose that convention

**Comment by Zspecial** [comment]
Unsubscribe me please

💞§¤Coi-P90Percy-Tayz¤§💞

**Comment by blunan** [comment]
Thanks for you quick response naddaf. I guess the problem is somewhere else as when I reach the onPlayPauseClicked(View v) method mState is PAUSED and not IDLE as you comment. Do I have to implement this media status update of IDLE with reason=canceled in my receiver or is it done by the cast libraries? My current onPause function in the receiver is the one from the CastReferencePlayer:
```javascript
videoPlayer.CastPlayer.prototype.onPause_ = function() {
    this.log_('onPause');
    this.cancelDeferredPlay_('media is paused');
    var isIdle = this.state_ === videoPlayer.State.IDLE;
    var isDone = (this.mediaElement_.currentTime === this.mediaElement_.duration);
    var isUnderflow = this.player_ && this.player_.getState()['underflow'];
    if (isUnderflow) {
        this.log_('isUnderflow');
        this.setState_(videoPlayer.State.BUFFERING, false);
        this.mediaManager_.broadcastStatus(/* includeMedia */ true);
    } else if (!isIdle && !isDone) {
        this.setState_(videoPlayer.State.PAUSED, false);
    }
    this.updateProgress_();
};
```

**Comment by naddaf** [comment]
You need to implement that yourself in your custom receiver when you are working with live stream.

**Comment by homburg** [comment]
For others trying to use the CastReferencePlayer and CastCompanionLibrary on android, see this patch:  https://github.com/googlecast/CastReferencePlayer/pull/23/files
