### ISSUE TITLE
Incorrect behaviour when resuming a paused livestream via the Minicontroller

### ISSUE THREAD

**Issue by michaelbarlow7** [googlecast/CastCompanionLibrary-android#302]
When casting a livestream, pressing the pause button on any of the provided control methods pauses as expected.

However, when pressing play via the MiniController it simply shows the circular progressbar over the ImageButton and playback does not resume. Pressing play via the notification/lockscreen controls or VideoCastControllerActivity resumes playback as expected.

The code on the sender app that applies here is [VideoCastManager.java](https://github.com/googlecast/CastCompanionLibrary-android/blob/master/src%2Fcom%2Fgoogle%2Fandroid%2Flibraries%2Fcast%2Fcompanionlibrary%2Fcast%2FVideoCastManager.java) at line 317 (onPlayPauseClicked()). The logic for determining the action here is different to the logic used by the notification and VideoCastControllerActivity.

I considered submitting a pull request but the pdf documentation implies that the logic might be correct, and actually the receiver app should be sending back the MediaStatus.PLAYER_STATE_IDLE status when pausing a livestream. I'm the [sample receiver app](https://github.com/googlecast/CastReferencePlayer) with very minimal changes...perhaps the issue should be corrected there?

**Comment by naddaf** [comment]
CCL, as you noticed, assumes that a "pause" state for a live stream is identified by an IDLE state with a particular value for IDLE_REASON. So you have two options:
1. Change CCL: it is pretty straightforward to make a change in the relevant part of the CCL
2. Write a custom receiver: the default/Styled/Reference receivers do not particularly handle live streams or at least not in this particular situation.

**Comment by michaelbarlow7** [comment]
Thanks for the fast reply.

I had a look at implementing no. 1 but I'm using the library as a gradle dependency, so unless I download and use CCL as a module it's a bit tricky as I'd have to either extend VideoCastManager, which doesn't feel like was made for this, or copy-paste the class itself. 

That said, I'm already using a custom receiver app, and it seems to be the right place to implement the fix, so I'll just do that. Thanks again.
