### ISSUE TITLE
Casting live video is not working

### ISSUE THREAD

**Issue by aravinds03** [googlecast/CastCompanionLibrary-android#307]
Hi,
I am trying to cast live video using CCL , but it is not working.
I have MediaInfo.setStreamType(live) . 
I have also tried to play the url using CastVideos-Android app, but even that app fails to cast.

Url: http://api.new.livestream.com/accounts/16628730/events/4628262/live.m3u8

**Comment by naddaf** [comment]
Just stating that my app doesn't work is really not that helpful. You'd need to explain what is not working, provide logs on receiver and sender, etc.

**Comment by aravinds03** [comment]
Sorry, I did not try to gather logs. When I did, I figured out root cause is due to CORS.
Closing this issue.
