### ISSUE TITLE
Failed to load media Toast Message

### ISSUE THREAD

**Issue by dmfrey** [googlecast/CastCompanionLibrary-android#308]
I keep getting this toast message in my app when using the CastCompanionLibrary. Logs are not showing any details. I have enableDebug enabled in my singleton, but I see nothing in the logs. I am using the VideoCastControllerActivity. Is there anything further I can enable?

**Comment by naddaf** [comment]
Edit LogUtils.java and set DEBUG to true.

**Comment by dmfrey** [comment]
Is it possible to enable this without modifying the code? I am pulling the
library in as a dependency from jcenter, not through a project reference.

**Comment by naddaf** [comment]
Unfortunately not at the moment. I am planing to have an update very soon so I'll see if I can make it easier to do so.

**Comment by dmfrey** [comment]
Thank you

**Comment by naddaf** [comment]
In v2.8.4, you should be able to enable CCL logging through CastConfiguration by calling enableDebug() when you instantiate VideoCastManager, or dynamically by calling LogUtils.setDebug(true).
