### ISSUE TITLE
 Getting Failed to resolve: com.google.android.libraries.cast.companionlibrary:ccl:2.8.4

### ISSUE THREAD

**Issue by honeal** [googlecast/CastCompanionLibrary-android#311]
Getting a failed to resolve when trying to update to the most recent version (2.8.4).

**Comment by naddaf** [comment]
Update how?

**Comment by honeal** [comment]
By changing the version number in my Gradle dependencies and sync'ing. I can compile 2.8.2 and 2.8.3 without issue.

**Comment by naddaf** [comment]
Try it again, see if that works now

**Comment by honeal** [comment]
Success

**Comment by naddaf** [comment]
Great, thanks for bringing that to my attention, there was an incorrect configuration which was causing that.
