### ISSUE TITLE
Use with GameManagerClient?

### ISSUE THREAD

**Issue by dbsleiman** [googlecast/CastCompanionLibrary-android#312]
To initialize a [GameManagerClient](https://developers.google.com/android/reference/com/google/android/gms/cast/games/GameManagerClient.html#public-methods), a `GoogleApiClient ` and `castSessionId` are needed. We can get the `castSessionId` from the `onApplicationConnected` of `DataCastConsumerImpl`, but there seems to be no way to get the `GoogleApiClient`. 

It would be great if it could be passed as an additional parameter of `onApplicationConnected` or if it was exposed through the `DataCastManager` class.

**Comment by naddaf** [comment]
You can (and in this should) use a separate client since apiClient, once instantiated, cannot change and add new APIs to it (like Games).
