### ISSUE TITLE
Appropriate position in layout xml for mini controller

### ISSUE THREAD

**Issue by dmfrey** [googlecast/CastCompanionLibrary-android#313]
I started to add the mini controller to my existing layouts. I included the mini_controller.xml in my layout, but the position ended up being underneath the ActionBar. I could only see it once I scrolled and the ActionBar shrunk. Is the mini_controller.xml appropriate to use in the CoordinatorLayout or in a DrawerLayout?  Do you just position it through the <include> state as you normally would?

**Comment by naddaf** [comment]
Mini controller should always be visible on the screen and the common place for that is at the bottom of the screen, it is simply a composite widget so it is up to you to decide what best works for your app to make it stay fixed at the bottom of screen regardless of the other layout changes.

**Comment by dmfrey** [comment]
Can it be hidden when not connected to a cast device?

**Comment by naddaf** [comment]
If you are dealing with videos, yes it should be hidden when you are not
casting (VideoCastmanager handles that) but if you are dealing with music,
it make sense for it to be visible both when casting remotely or playing
locally.
