### ISSUE TITLE
Catch when receiver disconnects from sender

### ISSUE THREAD

**Issue by Mugurell** [googlecast/CastCompanionLibrary-android#316]
Using   _com.google.android.libraries.cast.companionlibrary:ccl:2.8.4_   as a dependency.

I've really tried to catch when the user either exits the receiver app (with like pressing the home button)
or when the user disconnects from the notification, both with the sender application in background.

The app indeed disconnects, all is fine, but I can't seem to find a callback for this.

Case in point, I want to use it for a streaming radio app. So when the receiver disconnects I want to resume playback on sender device, or at least if would be nice to know when this happens.

When the receiver disconnects (from a Nexus Player) probably because
`E/ccl_VideoCastManager: [v2.8.4] Failed to get volume
com.google.android.libraries.cast.companionlibrary.cast.exceptions.NoConnectionException`
i catch no other callbacks,
And when disconnecting from the notification, although with debug enabled there are many things happening, I can't see no callbacks for this.

I think offering this functionality is useful and needed.
Can it be done?

**Comment by Mugurell** [comment]
A hacky solution I've found is to extend the VideoCastNotificationService and trigger something in it's onDestroy().
Works for now, for my particular situation, but I feel there must be a better way.

**Comment by naddaf** [comment]
Can't you use BaseCastConsumer#onDisconnected(reason):

   ```
 /**
     * Called when a device is disconnected or fails to reconnect and provides a reason for the
     * disconnect or failure.
     *
     * @param reason The failure/disconnect reason; can be one of the following:
     * <ul>
     *     <li>{@link BaseCastManager#DISCONNECT_REASON_APP_NOT_RUNNING}</li>
     *     <li>{@link BaseCastManager#DISCONNECT_REASON_EXPLICIT}</li>
     *     <li>{@link BaseCastManager#DISCONNECT_REASON_CONNECTIVITY}</li>
     *     <li>{@link BaseCastManager#DISCONNECT_REASON_OTHER}</li>
     * </ul>@BaseCastManager.DISCONNECT_REASON
     */
    void onDisconnectionReason(@BaseCastManager.DisconnectReason int reason);
```

**Comment by Mugurell** [comment]
Working. Thanks. Sorry. You're doing a great job!
