### ISSUE TITLE
Cast Controller UI does not update after playing next Media in queue

### ISSUE THREAD

**Issue by tranxuandat** [googlecast/CastCompanionLibrary-android#320]
Sender Controller UI like: Media title, Media Art Background and Media length is not update after next media is played on ChromeCast.
I can see the callback onMediaQueueUpdated is called but nothing is update with UI.
Testing with CCL 2.8.3.

**Comment by naddaf** [comment]
I just tested  with CCL 2.8.4 and CastVideos-android and it works just fine. I suggest you check your application and your receiver (if you have a custom one).

**Comment by tranxuandat** [comment]
You are rite, my receiver is not set up properly. Thanks for your response.
