### ISSUE TITLE
VideoCastControllerActivity wont close on closing the cast from the CCL notification from the lock screen

### ISSUE THREAD

**Issue by tomas-paronai** [googlecast/CastCompanionLibrary-android#324]
[Original post](http://stackoverflow.com/questions/38478584/googlecast-minicontroler-onclose-listener?noredirect=1#comment64373712_38478584)

Open VideoCastControllerActivity from the minicontroller, lock your device, tap the small X on the notification, this will disconnect the device from the cast, unlock your device, still in the VideoCastControllerActivity. 
Maybe some access to a finish() method which I could for an example call from a VideoCastConsumer onDisconnected() method.

**Comment by tomas-paronai** [comment]
Is anyone looking at these issues? 5 months since last update.

**Comment by naddaf** [comment]
This is addressed in v2.9.0
