### ISSUE TITLE
IllegalStateException after restore activity

### ISSUE THREAD

**Issue by enigmadevs** [googlecast/CastCompanionLibrary-android#325]
I get this exception after activity has been destroyed and i try to return to it:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.enigma.xdede/com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerActivity}: java.lang.IllegalStateException: No VideoCastManager instance was found, did you forget to initialize it?

I tried this at on onRestoreInstanceState:

`if(mCastManager == null) {
                CastConfiguration options = new CastConfiguration.Builder(CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID)
                        .enableAutoReconnect()
                        .enableCaptionManagement()
                        .enableDebug()
                        .enableLockScreen()
                        .enableNotification()
                        .enableWifiReconnection()
                        .setCastControllerImmersive(true)
                        .setLaunchOptions(false, Locale.getDefault())
                        .setNextPrevVisibilityPolicy(CastConfiguration.NEXT_PREV_VISIBILITY_POLICY_DISABLED)
                        .addNotificationAction(CastConfiguration.NOTIFICATION_ACTION_REWIND, false)
                        .addNotificationAction(CastConfiguration.NOTIFICATION_ACTION_PLAY_PAUSE, true)
                        .addNotificationAction(CastConfiguration.NOTIFICATION_ACTION_DISCONNECT, true)
                        .setForwardStep(10)
                        .build();
                VideoCastManager.initialize(this, options);
                mCastManager.getInstance();
            }
            else {
                try {
                    VideoCastManager.getInstance();
                }
                catch (IllegalStateException e) {
                    CastConfiguration options = new CastConfiguration.Builder(CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID)
                            .enableAutoReconnect()
                            .enableCaptionManagement()
                            .enableDebug()
                            .enableLockScreen()
                            .enableNotification()
                            .enableWifiReconnection()
                            .setCastControllerImmersive(true)
                            .setLaunchOptions(false, Locale.getDefault())
                            .setNextPrevVisibilityPolicy(CastConfiguration.NEXT_PREV_VISIBILITY_POLICY_DISABLED)
                            .addNotificationAction(CastConfiguration.NOTIFICATION_ACTION_REWIND, false)
                            .addNotificationAction(CastConfiguration.NOTIFICATION_ACTION_PLAY_PAUSE, true)
                            .addNotificationAction(CastConfiguration.NOTIFICATION_ACTION_DISCONNECT, true)
                            .setForwardStep(10)
                            .build();
                    VideoCastManager.initialize(this, options);
                }
            }`

But it doesn't work, still getting same exception.

What should i do to keep the VideoCastManager instance alive after activity have been destroyed?

**Comment by naddaf** [comment]
The proper place for instantiating/initializing the cast manager is in your Application instance; that way it is not tied to a specific activity and as long as your application is running, it will be around. Take a look at the documentation for CCL; I believe it is mentioned there too.
