### ISSUE TITLE
Progaurd issue

### ISSUE THREAD

**Issue by girdharpatel** [googlecast/CastCompanionLibrary-android#331]
Hi,

My proguard is complaining abt below 2 things and I am failed to create release build.  Do we need to mention anything abt this library in my proguard.cfg file? Help here would be really appreciated.

Warning: com.longtailvideo.jwplayer.cast.CastManager: can't find referenced method 'void enableFeatures(int)' in program class com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager

Warning: com.longtailvideo.jwplayer.cast.CastManager: can't find referenced method 'com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager initialize(android.content.Context,java.lang.String,java.lang.Class,java.lang.String)' in program class com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager

**Comment by naddaf** [comment]
In your proguard config, you might want to exclude the classes that your project cannot find from obfuscation
