### ISSUE TITLE
Out of memory error for low end devices

### ISSUE THREAD

**Issue by takn** [googlecast/CastCompanionLibrary-android#333]
Hi, We're seeing this error happen often enough:

`This Crash occurred 123 times for 75 users
0 java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 5353726 free bytes and 5MB until OOM
1 at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
2 at android.graphics.Bitmap.nativeCreateFromParcel(Native Method)
3 at android.graphics.Bitmap.access$000(Bitmap.java:37)
4 at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1653)
5 at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1645)
6 at android.os.Parcel.readParcelable(Parcel.java:2246)
7 at android.os.Parcel.readValue(Parcel.java:2146)
8 at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
9 at android.os.BaseBundle.unparcel(BaseBundle.java:221)
10 at android.os.BaseBundle.putCharSequence(BaseBundle.java:441)
11 at android.os.Bundle.putCharSequence(Bundle.java:323)
12 at android.support.v4.media.MediaMetadataCompat$Builder.putString(MediaMetadataCompat.java:660)
13 at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSessionMetadata(VideoCastManager.java:2411)
14 at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerMetadataUpdated(VideoCastManager.java:2178)
15 at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$24.onMetadataUpdated(VideoCastManager.java:1833)
16 at com.google.android.gms.cast.RemoteMediaPlayer.onMetadataUpdated(Unknown Source)
17 at com.google.android.gms.cast.RemoteMediaPlayer.zzb(Unknown Source)
18 at com.google.android.gms.cast.RemoteMediaPlayer$1.onMetadataUpdated(Unknown Source)
19 at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
20 at com.google.android.gms.cast.internal.zzm.zzcf(Unknown Source)
21 at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
22 at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
23 at android.os.Handler.handleCallback(Handler.java:739)
24 at android.os.Handler.dispatchMessage(Handler.java:95)
25 at android.os.Looper.loop(Looper.java:145)
26 at android.app.ActivityThread.main(ActivityThread.java:6145)
27 at java.lang.reflect.Method.invoke(Native Method)
28 at java.lang.reflect.Method.invoke(Method.java:372)
29 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
30 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)`

It happens mostly on older devices, the highest incidence being on Galaxy S4 phones, which is pretty popular among our users. 

It appear that the OOM error happens when trying to decode the placeholder asset.

**Comment by naddaf** [comment]
Have you tried replacing the placeholder images with something smaller (or provide a number of them, with different sizes in different resource directories) in your own project? Those should override/replace the ones that are in the library when you build your project.

**Comment by naddaf** [comment]
Closing since haven't heard back.
