### ISSUE TITLE
Chromecast doesn't return information about duration and position.

### ISSUE THREAD

**Issue by PavelGP** [googlecast/CastCompanionLibrary-android#334]
On some devices (Nexus 9, Android 7) when call:
`VideoCastManager.loadMedia(mediaInfo, false, notNullPosition)`
autoplay = false, and not null position, we can't get actual duration and current position of player.

`VideoCastManager.getMediaDuration()`
returns -1;
`VideoCastManager.getCurrentMediaPosition()`
returns 0;

for some other devices it works good.

**Comment by naddaf** [comment]
I can't seem to find any code that could be device dependent; you need to debug that on your side and report the result.

**Comment by PavelGP** [comment]
Ok, I checked one more time on different devices and I have the same behaviour with position=0, duration = -1. We think that it is related to type of streams wich we use. We use live stream with DVR one hour. So may be CCL doesn't support this type of streams (increasing DVR stream).

**Comment by naddaf** [comment]
CCL doesn't "calculate" position, nor duration. Duration comes from the receiver and current position comes from the cast sdk.

**Comment by PavelGP** [comment]
Thanks!

**Comment by prakhardighe** [comment]
The total duration and duration played can be taken from the following way:

```
RemoteMediaClient remoteMediaClient = sCastSession.getRemoteMediaClient();
            if (remoteMediaClient == null) {
                return;
            }
            remoteMediaClient.addListener(new RemoteMediaClient.Listener() {
                @Override
                public void onStatusUpdated() {
                    MediaStatus mediaStatus = remoteMediaClient.getMediaStatus();
                    if (mediaStatus != null) {
                        long totalStreamDuration = mediaStatus.getMediaInfo().getStreamDuration();
                        long StreamPosition = mediaStatus.getStreamPosition();
                        .....
                    }
               }
               .....
           });
```
