### ISSUE TITLE
Latest version of Google Play services not supported

### ISSUE THREAD

**Issue by clivejefferies** [googlecast/CastCompanionLibrary-android#335]
The library is on Google Play services 9.0.0. As a result I cannot update Google Play Services in my own project.

**Comment by naddaf** [comment]
I don't think that would be an issue; if your own project provides a more recent version of the sdk, it will be used instead of the one here.

**Comment by clivejefferies** [comment]
Hi, 
    That is incorrect. There is an error in the Grade file when I try and change the version number.

Clive

**Comment by naddaf** [comment]
Which gradle file? Also, start using the newest CCL.

**Comment by clivejefferies** [comment]
Hi,
     The build.gradle file in my project. I have the CCL library import and any GPS imports. If the GPS imports are not at the same level as the cast import found in the CCL build.gradle. The GPS imports are underlined red as they are not at the same level.

Thanks,

Clive

**Comment by naddaf** [comment]
CCL library is using Cast SDK 9.8.0.

**Comment by clivejefferies** [comment]
It wasn't when I raised the ticket :).  I will use the updated version now. Thanks for your time and effort.

**Comment by naddaf** [comment]
Eve if the library is using a lower version of the SDK, you should be able to include the higher version of the same cast sdk (along with other components) in your own project and then library should fallback to the one that you have mentioned, or at least that is my understanding.

**Comment by clivejefferies** [comment]
It doesn't, that's what I keep trying to tell you.
