### ISSUE TITLE
Can't use CCL 2.9

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#337]
When I try to compile with the 9.8.0 Google Play Services it all works fine but when I try to use the CCL 2.9 update it complains that 9.8.00 doesn't exist. Is that double zero a typo? 

Thanks.

**Comment by naddaf** [comment]
Checking my m2repository, I see 9.8.00 directory under ~/<SDK_HOME>/extras/google/m2repository/com/google/android/gms/play-services. What do you see on your machine?

**Comment by mntgoat** [comment]
I see 9.8.0

**Comment by naddaf** [comment]
I'll try to remove and update my repo again and if that changes to 9.8.0, I will create another update to reflect that.

**Comment by naddaf** [comment]
Ok, removing and adding the repo again created 9.8.0; I have updated the CCL to 2.9.1 to reflect that and published a new AAR file to jcenter.

**Comment by naddaf** [comment]
On my side, I have to use 00 otherwise it doesn't recognize it. I'll look
into it to see what is happening.
