### ISSUE TITLE
MetaData not updated upon network rediscovery.

### ISSUE THREAD

**Issue by TordWessman** [googlecast/CastCompanionLibrary-android#340]
Steps to reproduce:

1. Cast from two devices (A & B) to same device (playing the same resource).
2. Disconnect A from WiFi.
3. Change video resource on B.
4. Reconnect A to WiFi.
5. [For testing purposes in this case] Delay for 10 seconds (In order to make sure a (possible) background update process gets the time it needs to fetch information).
6. Check VideoCastManager.getRemoteMediaInformation()

Expected result:

VideoCastManager.getRemoteMediaInformation() should return the updated MediaInfo (belonging to the new resource B did chose).

Actual result:

VideoCastManager.getRemoteMediaInformation() returns meta data for the previous asset known to A.

**Comment by naddaf** [comment]
I don't think that is the case. If you look at the source for that method, you'll see that it doesn't rely on any cached information; it obtains the data from the SDK directly. If you believe there is an issue in the cast sdk, please open a ticket for that component.
