### ISSUE TITLE
VideoCastControllerActivity SeekBar does not update after first init

### ISSUE THREAD

**Issue by tomas-paronai** [googlecast/CastCompanionLibrary-android#347]
How to reproduce:

1. Connect to receiver
2. Start casting -> VideoCastControllerActivity opens in the sender app
3. SeekBar does not update. After I hit pause then play (or skip to another media in the playlist), it updates.

**Comment by naddaf** [comment]
I am not able to reproduce this with CastVideos-android-v2 app.
