### ISSUE TITLE
HLS with embed subtitles

### ISSUE THREAD

**Issue by tomas-paronai** [googlecast/CastCompanionLibrary-android#351]
Hello. 
We would like to add support for subtitles to our app chromecast. We are using HLS streams with embed subtitles in our local player and it is working fine. We do have some streams with no subtitles as well. 

When we start casting a stream with subtitles it does not work. It fails to load media with error code 2010. If we cast stream without the subtitles it is working.

We are using styled receiver.
We have enableCaptionManagement() set in the conf in our app. 

I also tested the streams with CastVideos-android-v2 app and the same thing happens:
Starts loading the video but then after aprox 2s stops and returns error code 2010.

**Comment by naddaf** [comment]
You'd need to look at your receiver logs and see what is happening on the cast device; this is not related to the sender.
