### ISSUE TITLE
Cast button doesn't work in menu popup

### ISSUE THREAD

**Issue by gtwelve** [googlecast/CastCompanionLibrary-android#352]
When showing the cast button in the menu popup like below:

app:showAsAction="never"

The cast button still appears in the list but when you click on it nothing happens. Is this a limitation of the library do I need to do something extra to wire it up?

This can be replicated by changing app:showAsAction="never" in the sample app:
https://github.com/googlecast/CastVideos-android

![example](https://cloud.githubusercontent.com/assets/1524427/25057663/e0141b48-21c5-11e7-9c66-121150ca5f96.jpg)

**Comment by naddaf** [comment]
CastVideos-android that you have linked doesn't use CCL.

**Comment by gtwelve** [comment]
Good point. In the Readme of this library it mentions that the CastVideos-android project uses this library. Maybe the Readme should be updated. 

I have the same issue with the sample app so it sounds like my problem is not with this library. Thanks for pointing that out.
