### ISSUE TITLE
MiniBar on click does not open work when using component, However MiniControllerFragment works

### ISSUE THREAD

**Issue by swizzersweet** [googlecast/CastCompanionLibrary-android#353]
Expected:
When the user clicks (or taps) on the minibar container (not a button), the user is supposed to be navigated to the fullscreen controller (ExpandedControlsActivity). This does not happen when the app in question is using the component in the layout, rather than the MiniControllerFragment.

Does not work:
```
            <com.google.android.libraries.cast.companionlibrary.widgets.MiniController
                android:id="@+id/miniController"
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom"
                android:layout_alignParentBottom="true"
                app:auto_setup="true"
                android:visibility="gone"/>

```

However, the container click works when using the MiniControllerFragment (From cast-videos-android)
```
            <fragment
                android:id="@+id/cast_mini_controller"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:visibility="gone"
                app:castShowImageThumbnail="true"
                class="com.google.android.gms.cast.framework.media.widget.MiniControllerFragment" />
```

However, MiniControllerFragment uses cast_mini_controller.xml which does not allow me to change the position of the loading progress loader as seen in this screenshot

![progress_loader](https://cloud.githubusercontent.com/assets/1304446/25722974/1aa37448-30e4-11e7-9881-e806aa49bc25.png)

**Comment by naddaf** [comment]
Looks like you are mixing CCL with v3 sdk?? If you are using v3 sdk, then you shouldn't be using CCL and vice versa.
