### ISSUE TITLE
VideoCastManager.getInstance().stop() breaks the player permanently

### ISSUE THREAD

**Issue by casolorz** [googlecast/CastCompanionLibrary-android#356]
I modified the CastVideos code (the one that uses CCL) to add a stop button that calls `VideoCastManager.getInstance().stop()` and when you press that, the video player on the Chromecast just goes black and it will not accept any new videos.

**Comment by naddaf** [comment]
stop() unloads the media so that is why screen goes black and doesn't accept, say, "play" again unless you load the media again. That is the intended behavior. If you want, you can use "pause"

**Comment by casolorz** [comment]
I am playing media again and it won't play. Like I said, it won't accept any new videos.

**Comment by naddaf** [comment]
And as I said, you'd need to load the media first.

**Comment by casolorz** [comment]
Is that not what "Play now" does on the cast videos application?

**Comment by casolorz** [comment]
Just to make sure the metadata is being loaded since that app uses queues and I'm not very familiar with them, I modified some of the code. 

I changed the code that plays the video, commented is what it did before:

```
 //   ((CastApplication) context.getApplicationContext())
//         .loadQueue(newItemArray, 0);
MediaQueueItem item = newItemArray[0];
VideoCastManager.getInstance().loadMedia(item.getMedia(),true,0);
```

The first video plays fine. If I play more videos without stopping they work fine. If I call `VideoCastManager.getInstance().stop()` then no videos will play again.

**Comment by naddaf** [comment]
What is the firmware of your chromecast?

**Comment by casolorz** [comment]
1.24.88007

I noticed this issue because my app (based on CCL and Cast Reference Player) has a stop button and all of the sudden my users have started complaining that they can't cast videos after hitting stop. I haven't done any production updates to my app or receiver in several weeks. 

I have tested 3 other apps that also have a stop button and they all exhibit the same issue.

**Comment by naddaf** [comment]
Is this post from you:
https://stackoverflow.com/questions/44125585/chromecast-audio-firmware-1-24-88047-broken

**Comment by casolorz** [comment]
Nope, but it sounds very similar to my issue but with audio. I don't do any audio. 

This one is mine https://issuetracker.google.com/issues/62055651

This is a fairly recent issue with more users emailing me every day, how long ago was 1.24.88007 released and is it already at 100% roll out?

Thanks.
