### ISSUE TITLE
 java.lang.IllegalStateException: No connection

### ISSUE THREAD

**Issue by KalpeshSangani** [googlecast/CastCompanionLibrary-android#360]
When i cast a video from my app using chrome cast it works awesome first time, It plays all video, but when i stop the casting and again connect for the cast video it gives me error '**java.lang.IllegalStateException: No connection**'  in my code when it call this line

> remoteMediaClient.queueLoad(queueArray, 0, REPEAT_MODE_REPEAT_OFF, null);

Below is the whole error log is mention.
Please give me some solution for this.

> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                           Process: com.controlcastappplayer, PID: 25879
>                                                                           **java.lang.IllegalStateException: No connection**
>                                                                               at com.google.android.gms.cast.framework.media.RemoteMediaClient.zzakq(Unknown Source)
>                                                                               at com.google.android.gms.cast.framework.media.RemoteMediaClient.queueLoad(Unknown Source)
>                                                                               at com.google.android.gms.cast.framework.media.RemoteMediaClient.queueLoad(Unknown Source)
>                                                                               at com.controlcastappplayer.fragments.ControlCastPlayerFragment.queuePlay(ControlCastPlayerFragment.java:1354)
>                                                                               at com.controlcastappplayer.fragments.ControlCastPlayerFragment$12.onSessionStarted(ControlCastPlayerFragment.java:827)
>                                                                               at com.google.android.gms.cast.framework.zzr.zzb(Unknown Source)
>                                                                               at com.google.android.gms.cast.framework.zzo$zza.onTransact(Unknown Source)
>                                                                               at android.os.Binder.transact(Binder.java:380)
>                                                                               at py.b(:com.google.android.gms.DynamiteModulesC:20)
>                                                                               at xy.a(:com.google.android.gms.DynamiteModulesC:22)
>                                                                               at yq.a(:com.google.android.gms.DynamiteModulesC:174)
>                                                                               at yn.a(:com.google.android.gms.DynamiteModulesC:50)
>                                                                               at wq.a(:com.google.android.gms.DynamiteModulesC:65)
>                                                                               at xf.onTransact(:com.google.android.gms.DynamiteModulesC:20)
>                                                                               at android.os.Binder.transact(Binder.java:380)
>                                                                               at com.google.android.gms.cast.framework.zzh$zza$zza.zza(Unknown Source)
>                                                                               at com.google.android.gms.cast.framework.CastSession$zza.zza(Unknown Source)
>                                                                               at com.google.android.gms.cast.framework.CastSession$zza.onResult(Unknown Source)
>                                                                               at com.google.android.gms.internal.zzpt$zza.zzb(Unknown Source)
>                                                                               at com.google.android.gms.internal.zzpt$zza.handleMessage(Unknown Source)
>                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                               at android.os.Looper.loop(Looper.java:135)
>                                                                               at android.app.ActivityThread.main(ActivityThread.java:5343)
>                                                                               at java.lang.reflect.Method.invoke(Native Method)
>                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
>                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by entertailion** [comment]
CCL is not recommended for new development because it is only for Cast SDK v2. We recommend you migrate to Cast SDK v3 (Cast Application Framework). Also see the Cast SDK v3 guide: https://developers.google.com/cast/docs/android_sender_setup

**Comment by KalpeshSangani** [comment]
I didn't get your point, how it related to my issue. Please guide me i am stuck in this issue.
