### ISSUE TITLE
Library not compatible with Support Library v27.0.0+

### ISSUE THREAD

**Issue by caleb-allen** [googlecast/CastCompanionLibrary-android#362]
CCL uses `android.support.v7.NotificationCompat` which was [removed from the support library](https://developer.android.com/topic/libraries/support-library/revisions.html#27-0-0) starting with 27.0.0.

This can be fixed by simply migrating to the v4 version of the support library

**Comment by entertailion** [comment]
CCL is not recommended for new development because it is only for Cast SDK v2. We recommend you migrate to Cast SDK v3 (Cast Application Framework). Also see the Cast SDK v3 guide.

**Comment by casolorz** [comment]
Unfortunately v3 of the sdk does not allow for custom connect dialogs and a lot of apps have spent a lot of time and money on their connect dialogs. Some apps would have to completely redesign the entire UI to use v3 because of this unnecessary limitation.

**Comment by caleb-allen** [comment]
We are working on upgrading to v3, is it possible to support v27.0.0 as a quick fix in the meantime? I understand if that wouldn't work

**Comment by entertailion** [comment]
CCL is no longer maintained. Feel free to fork your own copy to make any changes you need.
